### ISSUE TITLE
Image looks blurry after installing "acs-aem-commons-content-3.7.0"

### ISSUE THREAD

**Issue by mehrotraneha** [Adobe-Consulting-Services/acs-aem-commons#1019]
Hi ,

In our application after installing ACS AEM Commons Content,images looks blurry if the image is resized to (width)105*140(height)

Here i am attaching the zip file ,which contains - 

1. ACS AEM Commons-Named Image Transformer Factory which contains the configuration we are using.
2. The original image
3. The blurred image,after implementing the change.

The issue can be reproduced as mentioned below -

1. Install the acs-aem-commons-content-3.7.0
2. Drag the image component
3. Resize its size to 105*140 pixels

Expected Result - The image should not be blurred
Actual Result - The image is blurred

Thanks
Regards,
Neha
[blurredimages.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1057364/blurredimages.zip)

**Comment by davidjgonzalez** [comment]
sorry - im not clear what the actual image being resized are; can you provide the actual source image and the actual resized image? Is it JUST the pants + shoes? or is it more?

If you take the source image, bring it into photoshop (or some similar tool) and resize down to the target size, does it appear blurred? TBH, cant tell where the blurring is occurring.

Also, are you sure you arent converting from a jpg -> png or something? (this is where the actual files come in handy since i cant tell whats going on from just screenshots)

The quality flag is actually not great, IIRC it maxes out at ~82, and after that the internal libs it depends on has some bug where it balloons file size and decreases quality (???) -- this should be noted in the docs tho.

**Comment by davidjgonzalez** [comment]
@mehrotraneha any more info on this issue?

**Comment by davidjgonzalez** [comment]
Closing due to lack of info; Please re-open if you continue to have the problem and can provide the requested details
