### ISSUE TITLE
Issue with versioned clientlibs

### ISSUE THREAD

**Issue by rgummalla** [Adobe-Consulting-Services/acs-aem-commons#1206]
ACS Commons 3.10.0.
AEM 6.3 Sp1/TarMK

In the XXX-common package, the clientlibs will be updated. Customer do see the updated code deployed to author & publish. The libraries are referenced in a page template.
Customer is using versioned client libs from ACS Commons 3.10.0
 
When customer deploys the package and when the clientlibs update, and a new hash version exists, Customer does not see the updates on pages using the template until they re-activate them. They do not appear to be flushed in the dispatcher, but even after flushing the dispatcher manually, they are rendered with the old clientlibs reference until they are reactivated.
 
Can you help us investigate the cause of these behaviours?

**Comment by justinedelson** [comment]
In general, this sounds like the expected behavior and has nothing to do with ACS AEM Commons. In general, when you deploy code the dispatcher cache will also need to be invalidated. Otherwise, the HTML previously generated by the old code is still cached.

That said, the description is obscured through pronouns and potentially incorrect terminology. Please clarify. Specifically:

> The libraries are referenced in a page template.

How so? Is this a static template - in which case there's no way to refer to a client library from a template? Or an authorable template?

> Customer does not see the updates on pages using the template until they re-activate them. 

What is reactivated? The template or the pages?

> They do not appear to be flushed in the dispatcher, but even after flushing the dispatcher manually, they are rendered with the old clientlibs reference until they are reactivated.

What does "they" refer to here?

**Comment by kwin** [comment]
Maybe you run into the issue outlined in #1208.
