### ISSUE TITLE
Upgrading from AEM 6.1 to 6.3 is failing with Caused by: java.io.IOException: Unable to get component of class 'interface org.apache.sling.rewriter.Transformer' with type 'versioned-clientlibs'.

### ISSUE THREAD

**Issue by stephanieacs** [Adobe-Consulting-Services/acs-aem-commons#1227]
I am trying an inplace upgrade from 6.1 to 6.3. I replaced the 6.1 jar with 6.3 and performed 3 steps. 
1) unpack the jar  --- SUCCESS
java -Xmx4096m -jar aem-quickstart-6.3.0.jar -unpack
2) migrate the datastore to the new version  --SUCCESS

java -Xmx4096m -XX:MaxPermSize=2048m -jar aem-quickstart-6.3.0.jar -v -x crx2oak -xargs -- --load-profile segment-fds --src-datastore=......./author/crx-quickstart/repository/repository/datastore

3) Perform the upgrade -- FAILING I THINK
java -server -Xmx4096m  -Djava.awt.headless=true -Djava.io.tmpdir=/***/..**/tmp -Dsling.run.modes=author,dev,crx3,crx3tar -jar crx-quickstart/app/cq-quickstart-6.3.0-standalone-quickstart.jar start -c crx-quickstart -i launchpad -p 4552 -Dsling.properties=conf/sling.properties 

The felix console bundles all are active except for the ACS Commons bundle. I read online that we need a 3.X version for that but whenever I hit any page other than /system/console/bundles, they result in a 500 error with a message in the logs that say 

"Caused by: java.io.IOException: Unable to get component of class 'interface org.apache.sling.rewriter.Transformer' with type 'versioned-clientlibs'."

I wanted to upload the new 3.X version for acs-commons but I am unable to reach the /crx/packmgr . 

I am not sure if I am missing any steps for the upgrade process. Kindly provide your insights.

**Comment by justinedelson** [comment]
What that error indicates is that the `versioned-clientlibs` is a required transformer in the rewriter pipeline, but since the ACS AEM Commons bundle is not active, the rewriter pipeline is failing. As you note, you will need to install a version of ACS AEM Commons compatible with 6.3. You have three choices that I can think of:

* Temporarily remove the `versioned-clientlibs` transformer from the pipeline (and then install the correct package via the Package Manager web interface).
* Install the ACS AEM Commons package using the Package Manager HTTP API.
* Install the ACS AEM Commons package via the file system.
