### ISSUE TITLE
URL Asset import should handle spaces and other invalid characters

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1395]
Right now there are errors thrown if a URL has spaces in it.  At the minimum those should be converted to %20, but ideally other invalid characters should be converted as well.

**Comment by ahmed-musallam** [comment]
@davidjgonzalez @badvision this issue is major, actually. Consider this scenario:

on a remote server, I have an asset with full url: 

`http://my.domain.com/path/to/my%20asset.png`

On the spreadsheet, I have to enter the *encoded* URL, ie:`http://my.domain.com/path/to/my%20asset.png`. If I enter the decoded url: `http://my.domain.com/path/to/my asset.png`, an `IOException` will be thrown due to an illegal character  (the white space).

So, I add the *encoded* url to the spreadsheet:
`http://my.domain.com/path/to/my%20asset.png` with target: `/content/dam/path/to`

The import is succeeds. However, the asset *node name* in JCR will be: `my%20asset.png` and this means two things:

1. Using the following URL wont resolve the asset: `/content/dam/path/to/my%20asset.png` because the url will be decoded and the expectation is that the asset node name would contain a space and not the literal `%20`: `/path/to/my asset.png`
2. in order to access this asset, I would have to double encode the url to: `/content/dam/path/to/my%2520asset.png` so that when it's decoded, the JCR path that will be resolved would be  `/content/dam/path/to/my%20asset.png`


**I'd think an easy fix would be to expect un-encoded URLs in the spreadsheet and encoding them before sending the request to download the asset**

**Comment by ahmed-musallam** [comment]
FYI: I created a rudimentary [groovy console](https://github.com/icfnext/aem-groovy-console) script to decode asset names to mitigate this issue, for now:

https://gist.github.com/ahmed-musallam/32a82ae4721771bd63811484c476695c
