### ISSUE TITLE
Package per feature

### ISSUE THREAD

**Issue by pacoolsky** [Adobe-Consulting-Services/acs-aem-commons#142]
Number of features is growing and some of the features are quite independent of others. Lets assume I would like to use single feature e.g. Flush Rules only, I have to install the whole package. Would it possible to have package per feature, so I can install only these "plugins" which I would like to use ?

**Comment by stefanseifert** [comment]
i would also greatly prefer having different bundles per feature. indeed not having this is currently the reason we hesitate to use it in our projects.

ACS commons currently has over 50 different features. in a typical project we could perhaps need 2-5 of them. yes, this will be a "random pick", but still only a small subset.

splitting up into bundles will be a huge one-time effort (as always when you split up a monolith into single features). you can still release all bundles at once to keep the release process lean, and of course still provide an AEM content package containing all features as today. if the individual features are provided as OSGi modules in the maven repo projects could pick to use only some of them and do the bundling on their own side. (this would be easier if the JCR content of each feature are included in the OSGi bundle as sling initial-content, and not as a separate AEM package)

what are my main reasons to wish different bundles per features?

1. in general i want to install as few features/customizations on our customer systems as possible. i have no time to test all of them to check whether they are compatible with our projects and other libraries or not. i trust that you do the best job you can to make them "unobstrusive", but we are the first that have a problem when it's not the case; and if our project already depends on ACS commons we cannot simple remove it again if there is a problem with an unused feature.
2. perhaps i have a better solution for some of the features provided in ACS commons, but still want to use some others (e.g. http://wcm.io/sling/models/ vs. ACS commons AEM Objects Sling Models Injector). then i do not want to deploy both of them.
3. some bundles of ACS commons/tools do not start when additional third-party dependencies are not available. afaik this was solved in ACS commons with the introduction of the "min" variant, but for ACS tools this problem is still present. generally and from OSGi-perspective this is not a problem. but if you have an operations team on the customers side that is - well - not-so-well-trained - you need simple rules for them. like "make sure all bundles are active, if not there is a problem". having to explain them for which it is a problem and for which not sometimes overstrain them. same applies to monitoring tools just looking at all bundles statuses.

btw. - the same applies to ACS tools.

**Comment by justinedelson** [comment]
Not sure I understand the first point. If there is a feature which is overy obtrustive, where is the Issue/PR to fix that? This would, IMHO, be significantly more efficient than the solution you are suggesting.

Initial-content does not meet our requirements with respect to filtering or (soon) access control.

Also, ACS AEM Tools provides a min package now, so I don't really understand the problem in the third point.

**Comment by stefanseifert** [comment]
i was not aware AEM tools provides a min package as well, i created a PR to make it more obvious on the site: https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/34

**Comment by davidjgonzalez** [comment]
Closing as this isnt the project paradigm; nice discussions tho!
