### ISSUE TITLE
[Discussion] AEM Commons to support context-aware config?

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Consulting-Services/acs-aem-commons#1508]
Is there any plans and/or timeline set out for AEM commons to begin using Sling's [Context-Aware Configuration](https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration.html) instead of the current OSGi config setup?

Specifically, this question applies to anything that may be different per site/per tenant. To me it seems to be a logical next-step, but I do understand that it would be quite a significant change, not only for the code base, but for the users too.

(There was no Disqus comment section on the AEM Commons homepage, so I opted to post here for visibility.)

**Comment by ahmed-musallam** [comment]
I'd Also love to see that happen!

**Comment by badvision** [comment]
The next version is going to support 6.3+ only so this is possible.  I'd love to see a PR on this.

**Comment by davidjgonzalez** [comment]
There are a few issues here:

1) When you say CA Config-based rather than OSGi config based... we typically use OSGi configs to enabled features. So SOME OSGi config (even an empty config) will likely be required (since CA Config can't stop a @Component from activating AFIAK). 

2) There is not simple/sane tooling for building out CA Config consoles in AEM (wcm.io has something but we try to avoid requiring 3rd party dependencies)

3) I expect this would require quite a bit of refactoring of existing functionality (and a bit of thought thinking of backward compatibility) - since OSGI configs are usually read a @Activate while CA Configs shine in the context of a resource path (which @Activate doesn't have - unless we move to /apps/settings/acs-commons ... which TBH, im not sure there's a material difference to OSGi config)

That being said, new features can certainly use CA Config - For example, the PWA feature i had been working w Avijt with has a CA Config: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1536

**Comment by joerghoh** [comment]
A feature where CA Config would definitely help is the Error Page Handling. And there are definitely other features, where it could be useful.

I don't think that there is a general dissens about using CA Config, but it should be reviewed per feature. So I suggest to close this ticket and instead open more specific ones.

**Comment by badvision** [comment]
Agree @joerghoh
