### ISSUE TITLE
Blurry Images using Named Transform Image Servlet

### ISSUE THREAD

**Issue by deadline98** [Adobe-Consulting-Services/acs-aem-commons#1541]
## Required Information

* [x ] AEM Version, including Service Packs, Cumulative Fix Packs, etc:  6.3.2.2
* [x ] ACS AEM Commons Version: 3.2
* [x ] Reproducible on Latest? yes (just tried with 3.18.x)

### Expected Behavior

When I use the built in Named Transform Image Servlet, I expect to get the new transformed image in an acceptable/comparable quality. Especially when only using 1 transform operation. (Tried with Resize and Bounded Resize)

### Actual Behavior

When I use the built in Named Transform Image Servlet, the returned image is very blurry for what the file size is. Using Photoshop on the same picture, and saving it with a quality that matches the file-size, the quality in Photoshop is significant better.

### Steps to Reproduce

Follow instructions on https://adobe-consulting-services.github.io/acs-aem-commons/features/named-image-transform/index.html to implement the sling osgi config.

Upload good quality picture with high resolution (2880x1000).

Apply transform to image by adding URL configs/params.

Resulting image is blurry.

### Links
Find in the zip: Original picture called `plane-l-2.jpg` and the transformed image `plane-2880.jpg`.
[assets.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2541812/assets.zip)

The weird part is, I've just added the 2880x1000 transformation as a config, so the exact same resolution as the original picture , and still just the compression (?) makes the picture blurry. That's at least what I guess because we're using the default implementation of AEM and ACS.

**Comment by badvision** [comment]
This is really more to do with how Java image scaling works, unfortunately.  There's a good discussion about it here: https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality

Please feel free to submit a PR if you'd like to help us expand the selection of resize filters. ;)

**Comment by davidjgonzalez** [comment]
@deadline98 i think i know whats going on ...

I suspect the crux of your problem is youre uploading hi-res images to AEM Assets, and using the default, OOTB DAM Update Asset workflow to rendition their Web Rendition (which creates a 1280 wide rendition).

ACS Commons Named Image Transform by default operates on the Web rendition, since it's the Web rendition after all and the intent of it is be used in the web context, the original is the "hi res" original, and usually too hi-res for normal use.

So the Named Image Transform is ACTUALLY operating on the 1280 web rendition and not youre hi-res image. Check to see the quality of THAT rendition in AEM Assets first since this is now your "source" image. If that web rendition is too small, or of a poor quality then NIT will never do "better" than that.

![image](https://user-images.githubusercontent.com/1451868/47919000-a29c4600-de84-11e8-8f73-3f9fb625b3c5.png)

You can experiment w/ this theory by changing the default rendition NIT uses to be: original per the screenshot below. I dont recommend doing this, since original can become very large, and can be inefficient to rendition on request -- the correct solution (assuming this is infact the problem) is to configure your web renditions via the DAM Update Asset WD to be the appropriate size/quality for your "web" use.

![image](https://user-images.githubusercontent.com/1451868/47919082-d5ded500-de84-11e8-9159-0ef72a2642b0.png)

**Comment by deadline98** [comment]
Thanks for your answer @davidjgonzalez! So I've done some testing and using `original` in NIT only helps for the original resolution. So lets say I take the airplane again in an original resolution of 2880x1000 and use `original` in the default rendition NIT, only the transformed image of 2880 is sharp (probably because the NIT actually takes the original picture as is). The other renditions may be slightly better, but still far from acceptable. (e.g. 1440px)

To test the DAM vs NIT behaviour, we've changed the DAM Update Asset WD to save the image in 2880 for web use. The newly saved image in DAM (`{hash}.web.2880.2880` is sharp, but also quite big. Using NIT now on the new `web` image, still results in a blurry result. (e.g. generate 1440px from the big 2880px web image)

Could this be due to the Issue @badvision mentioned? I just wonder what the way to go is with transforming images on the fly.. it's hard to imagine, that all Java transformations result in blurry pictures.

It's not really an option for us to save all resolutions we will ever need using the DAM Asset Workflow, as we have hundreds/thousands of pictures and this will result in too much disk space. That's why we use NIT.

**Comment by davidjgonzalez** [comment]
I used the files in your assets_v2.zip for this ...

@deadline98 call me crazy but im having a hard time seeing the different between the original (2880w resized to 1440w by Photoshop, and what you provided as generated by NIT to 1440).

Even zooming in on both to 250% to really show dithering, etc. they look nearly identical to me?

![image](https://user-images.githubusercontent.com/1451868/48091075-b32b2400-e1d6-11e8-9969-9e66bf425885.png)

![image](https://user-images.githubusercontent.com/1451868/48091186-fb4a4680-e1d6-11e8-9908-c4c2b18eede5.png)

**Comment by deadline98** [comment]
Thanks again for the response, our AEM Team is currently not available so you can close this for now if you want and I'll get back to you / reopen if needed. We don't really have a solution because I think currently we do the transforms on the original which results in a big file size (just like you said)

**Comment by davidjgonzalez** [comment]
@deadline98 sounds good - definitely let us know. 

Just to reiterate (and totally understand if this ship has sailed), but generally speaking (NIT or not), you want to create web renditions that are >= the largest res image you're going to use on the Web, and then use NIT/OOTB Adaptive Image Servlet/etc. to resize down from that. A lot of plumbing in OOT AEM Sites will naturally try to use the Web rendition anyhow, so it's just good to follow that rule of thumb.

That said, if you already have a ton of assets renditioned at 1280w - I understand its non-trivial re-rendition the original to a larger web rendition and re-publish all these assets.
