### ISSUE TITLE
Deprecate and remove the "quickly" feature

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1767]
With the advent of Omnisearch in the AEM product itself (a few releases ago), I don't see a need for the "quickly" feature anymore.

We should deprecate it and after a few releases remote it quickly. There have not been any changes to it in the last years (when requesting the documentation, it will still forward you to AEM 6. 0 docs ...), and it also lacks proper test coverage.

**Comment by davidjgonzalez** [comment]
I'm fine w/ this, though if you use Quickly youll quickly realize that it and omnisearch are quick different (i assume you've never used it, correct?).
 
I'd be interested if you could check if there's anything w/ Omnisearch (via its supported extensions) to make it more useable in the way quickly is.

**Comment by joerghoh** [comment]
Actually I never used quickly, but just stumbled across when I saw that it has zero test coverage, and it does not look very well maintained (e.g the documentation lookup seems always be done against AEM 6.0, https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/quickly/operations/impl/DuckDuckGoDocsOperationImpl.java#L71).

I am fine to keep that in ACS AEM Commons, but then we need to increase test coverage :-)

**Comment by davidjgonzalez** [comment]
FWIW its better time spent focusing on _reported_ bugs, fixing those bugs with supporting tests, rather than writing tests for features that are not reported as buggy, especially if the feature hasn't/doesn't change often (i.e. this) the ROI on tests drops off a cliff - i'd focus on increasing code coverage for features that we know higher rate of evolution/bug reports (for example, MCP stuff seems to have many bugs reported and is updated more often).  

We already suffer for "issue-fatigue" to the point we now auto-close issues. :(

That said, I'd certainly be interested in deprecating this if we could integrate some of its nicer capabilities into Omnisearch (TBH, i don't love the underlying implementation anymore :))
