### ISSUE TITLE
Validation for Coral UI 3 pathfield not working in multifield

### ISSUE THREAD

**Issue by Yatharth20** [Adobe-Consulting-Services/acs-aem-commons#1768]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3.2 (6.3 SP2)
* [x] ACS AEM Commons Version: 3.19.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When using the deprecated "Multifield Extension" and granite/ui/components/coral/foundation/form/pathfield (Coral UI 3) inside it with 'required' property, dialog should save when path is select/enter in the field

### Actual Behavior

When path is selected/entered in the pathfield, validation should trigger and mark the field as validate, thus making the dialog submit button enable but the field is still marked as invalid. When 'Add field' button is pressed, the complete validation is triggered and then the older path field is marked as valid.

### Steps to Reproduce

Refer #1455

**Comment by davidjgonzalez** [comment]
@Yatharth20 and @Narayan15 - i assume there is a good reason youre using the deprecated ACS Commons Multfield extension rather than the recommended AEM Multifield?
Since the ACS Commons multifield is deprecated, it doesnt get much "update love" .. any chance one of you could PR a fix for this?

/cc @schoudry  in case he has any quick ideas to resolve.

**Comment by Vinayakh36** [comment]
@Yatharth20 
I facing similar issue in aem 6.5.3, can anyone explain how it could be resolved?
