### ISSUE TITLE
v4.0.0 does not store multifield values

### ISSUE THREAD

**Issue by aadams26** [Adobe-Consulting-Services/acs-aem-commons#1798]
## Required Information

* [X ] AEM 6.4.3.0
* [X ] ACS AEM Commons 4.0.0
* [X ] Reproducible on Latest? yes

### Expected Behavior
As a user, I expect to be able to use the multified component to create and store tabular data.

### Actual Behavior
After submitting dialog multifield does not store data.

### Steps to Reproduce
The HelpX article below is a good example of steps to reproduce. I am able to get this to work with *ACS AEM Commons 3.19.0*:
https://helpx.adobe.com/experience-manager/using/htl_tab_component.html

**Comment by davidjgonzalez** [comment]
@aadams26 is there a reason you are not using the OOTB AEM Composite Multi-field component?

**Comment by aadams26** [comment]
@davidjgonzalez following the HelpX tutorial

**Comment by davidjgonzalez** [comment]
@aadams26 I can’t speak to that article, but we (acs commons team) have deprecated our multi field widget since the introduction of the OOTB multi field and strongly recommend you use that. Ours actually has a history of fragility as well (tends to break when you put a “new” widget in it). Because it’s deprecated it’s doubtful anyone will pick up working on this issue either.

That said, for tabs you should be using the core components Tab component (https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/tabs.html)

I understand/appreciate the confusion though based on the direction from that article - the right solution IMO is to lot follow that article though (as its advice is dated). HTH!

**Comment by aadams26** [comment]
Very good, thanks @davidjgonzalez

**Comment by aadams26** [comment]
@davidjgonzalez I'm sorry, I was unable to review my code at the time of your response. I am using the OOB AEM Composite Multi-field component, not the ACS Commons multifield.

**Comment by davidjgonzalez** [comment]
@aadams26 oh - ok! So I guess if tabs component doesn’t work for you, then you should reach out to adobe support wrt to the issue w the ootb multifield.

Closing, but please reopen w/ details of this is infact related to acs commons (sounds like it isn’t). Thanks for the update tho!

**Comment by aadams26** [comment]
@davidjgonzalez the component works with 3.19 but not the latest 4 version which leads me to believe that this is an issue with ACS component compatibility with core AEM components/
