### ISSUE TITLE
Can't use Ensure Service user with acs commons email service user

### ISSUE THREAD

**Issue by gonzalo-calandria** [Adobe-Consulting-Services/acs-aem-commons#1802]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4.2
* [x] ACS AEM Commons Version: 3.17
* [x] Reproducible on Latest? don't know

### Expected Behavior

User acs-commons/email-service should have permissions over the config path

### Actual Behavior

User acs-commons/email-service doesn't have the permissions

### Steps to Reproduce

Using the following configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
          xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
          jcr:primaryType="sling:OsgiConfig"
          principalName="acs-commons-email-service"
          operation="add"
          ensure-immediately="{Boolean}true"
          aces="[type=allow;privileges=jcr:read\,rep:write\,jcr:addChildNodes\,jcr:removeChildNodes\,jcr:removeNode\,crx:replicate;path=/conf/myProject/settings/workflow/notification/email]"/>
```

What's going on with this? If I use another user, it works and the permissions are included but if I do it with this user it doesn't work. I've also tried using the `principalName=acs-commons/email-service`

**Comment by justinedelson** [comment]
FWIW, I don't know what the issue is (logs would probably help), but `principalName=acs-commons/email-service` is definitely incorrect. The `principalName` is `acs-commons-email-service`. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/home/users/system/acs-commons/email-service/.content.xml

**Comment by gonzalo-calandria** [comment]
> FWIW, I don't know what the issue is (logs would probably help), but `principalName=acs-commons/email-service` is definitely incorrect. The `principalName` is `acs-commons-email-service`. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/home/users/system/acs-commons/email-service/.content.xml

My issue is that I need to allow acs-commons-email-service with read permissions over the path /conf/myProject/settings/workflow/notification/email and I can't do it. I've setup the configuration file but the permissions are not added to the user. What am I doing wrong?

**Comment by davidjgonzalez** [comment]
@gonzalo-calandria did you ever figure this out? Or do you still need help?

**Comment by manidevaraj** [comment]
Maybe for others benefit, figured out the permission not being set is due to the ProtectedAuthorizable check for AEM and ACS Commons provided system user. Implementation could be found [here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/users/impl/AbstractAuthorizable.java#L61)
