### ISSUE TITLE
searchAndUpdateResourceType getting java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Ronald-Diemicke** [Adobe-Consulting-Services/acs-aem-commons#1803]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.2
* [x] ACS AEM Commons Version: 3.19.0
* [?] Reproducible on Latest? yes/no

### Expected Behavior
When using the various methods in the 'OnDeployScriptBase' - I should be able to manipulate nodes.

### Actual Behavior

With large repositories, this is causing issues where it runs out of memory (~47000 nodes is killing it on my local setup)

### Steps to Reproduce

Just have a large repository and try to replace the sling:resourceType of lots of nodes.

**Comment by henrykuijpers** [comment]
Is it possible for you to commit the session (or resource resolver) every n nodes? So, try executing your logic on batches of say 1000 nodes?

**Comment by Ronald-Diemicke** [comment]
@henrykuijpers - In my mind, that's the right way to do it, but the 'OnDeployScriptBase' class has methods like ''searchAndUpdateResourceType" - which, in my mind, should do what you're talking about by default...

**Comment by joerghoh** [comment]
Hm, Oak was designed to support large transactions as well and not to break with exceptions like this. Can you share example code?

**Comment by davidjgonzalez** [comment]
How large is the segment store (sum of the tar files sizes), and how much ram is available on the machine?

If this process pulls enough segment tar files into memory (by holding references to nodes therein), and the sum of these tar files sizes exceeds memory you can run into memory exhaustion issues. This is why it’s recommended you can fit your entire segment store in memory.

Since tar files don’t optimize the storage of nodes by proximity in the jcr, a walk of a large tree structure could very easily pull in many/most tar files into memory.

I hope you’re also running compaction to ensure your tar files are as small as possible.

**Comment by Ronald-Diemicke** [comment]
@joerghoh - I think the issue is that I'm using the ACS commons code to do this, mainly using the 'searchAndUpdateResourceType' method in the 'OnDeployScriptBase' class.

@davidjgonzalez - I'd need to check, this is my local I'm talking about but I'm trying to prove this out for our other environments. My local only has 8gb of ram, and I'm guessing I'm running into the issues you're talking about. As mentioned before, I was surprised that the 'searchAndUpdateResourceType' method didn't do something more failure resistant to update nodes in batches.

**Comment by davidjgonzalez** [comment]
@hitmaninwis was the intent to make this commit atomic? Since it’s an ondeploy script ... I assume if half the resources were updated and half weren’t would put you in an unfortunate situation (you’re stuck in limbo at that point) regardless if you roll back your code base or not.

Perhaps the batch size could be configurable?

**Comment by davidjgonzalez** [comment]
@Ronald-Diemicke i'd be interested to see what objects are holding onto the memory as well. If it's Oak segment or Node objects, its very likely the cause if you don't have enough memory.  @HitmanInWis may be delayed in responding since he (or at least should be :)) partying at Adobe Summit this week.

**Comment by HitmanInWis** [comment]
Hey everyone, sorry for being late to the party.  Yes, I was at Adobe Summit this week, so just now getting caught up :).

On-deploy scripts are by default meant to be atomic - if a script fails the framework actually executes a rollback.  This default approach is safest because the framework cannot know if any given script can safely execute incremental saves.

If we think it's necessary, we could add an optional "incremental commit" parameter to the `searchAndUpdateResourceType` function.  I dont think an OSGi config is necessarily appropriate here since the On Deploy Scripts framework technically has no insight into the scripts that are being run, many of which will be completely custom by the end developer using the tool.

**Comment by HitmanInWis** [comment]
To reiterate, On-Deploy Scripts and On-Deploy Scripts Framework are two different things.

The framework has no way of knowing anything about the scripts, and therefore performs only a single save (or rollback in case of failure) at the end of the transaction.  It has no idea if the script is updating 1 or 1 million nodes, nor does the framework have the ability to execute an incremental save since the script does not return control to the framework until it has completed.

Scripts are generally custom code written by the end user of the tool.  ACS Commons does have a few common util functions available to call from scripts, such as `searchAndUpdateResourceType`.  Within these scripts, a developer is free to do incremental saves if the developer deems them necessary.  As such, I can see adding a parameter of `incrementalSaveCount` or similar to `searchAndUpdateResourceType` to allow the end script writer using the ACS Commons util function to force incremental saves, but by *default* the util function should not inject incremental saves because it goes against the framework's default of being atomic.

**Comment by davidjgonzalez** [comment]
@HitmanInWis agree - I think atomic by default it the right and smart choice.

the more I think about it, and assuming my suspicion is correct, this bug doesn't make that much sense to me since it's not being executed in a real-life context - and if there is less RAM than segment store, there is a bigger more important issue that needs solving.  Any number of things could access data in such a way that pulls a large portion of segment tars into memory - incremental saves feels like sweeping the larger problem under the rug in a way.

That said I guess it could be handy to do incrementally save on local dev for smoke testing? Just doesn't seem like a feature that should be used for "real use" of this tool.

**Comment by Ronald-Diemicke** [comment]
Sorry - I’m just getting back from Summit myself. 

I agree with the notions on this thread for the most part.

While the rollback capability is nice, I’d like to make sure this script works locally first. Even in the context I’m intending to use this, I’d like to be able to do the transactions incrementally. If the drawback is that I can’t rollback, I think I’m ok with that as our strategy would likely be to go to a backup.
