### ISSUE TITLE
MCP GeneratedDialog doesn't support map fields

### ISSUE THREAD

**Issue by gauravjasiwal** [Adobe-Consulting-Services/acs-aem-commons#1870]
## Required Information

* [6.4.3 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [4.0.0 ] ACS AEM Commons Version: _____
* [ Yes] Reproducible on Latest? yes/no

### Expected Behavior

GeneratedDialog should support map field.

### Actual Behavior

Currently, it does not support map fields

**Comment by badvision** [comment]
By supporting map fields what do you mean exactly?  There has to be some kind of UI mapping paradigm that works in a universal sense across projects to be in ACS Commons.  If it's something specific to your project you might want to make your own solution and post it as a pull request to ACS Commons for review.

**Comment by badvision** [comment]
So there has to be some consideration here because this has to mimic the multifield but with the additional consideration of the map key.  Some examples:

- Tabs where each map key is a tab name, and a plus/add button is provided to add new entries.
- Simple multifield UI where the key is added as a section header for each entry
- Accordion fold, much like the tab idea

In each case the other part of the UI that isn't answered immediately in Granite Components is the ability to click an add button and provide a new tab name or select one from a list (in the case of enum maps, for example where the selection is already limited, or also in the case of a data select where a data source provides the list of allowed selections for the tab names.)

WDYT?
