### ISSUE TITLE
Feature Review: Fully automatic component dialogs

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1904]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4+

### Feature Brief

Building on the synthetic form generation in MCP, expand to let developers create component dialogs using just the sling models.  Basically, no more need to hand-edit cq:dialog nodes.

### How this would work

![image](https://user-images.githubusercontent.com/5144198/58193524-2f77e700-7c91-11e9-8162-f2c56b8dbff5.png)

This requires the introduction of an OSGi service factory, DialogResourceProviderFactory, which binds to all declared sling models (via AdapterFactory registered instances.)  If an adapter factory is an exported class and is a subclass of GeneratedDialog, then it is considered a candidate for this feature.

Candidate sling models are then inspected for their provided resource type.  This can be provided in the class-level annotation which is part of sling models.   This can also be provided in a getter method or field annotated accordingly as the resource type.

The resource type is then pre-pended with "/apps/" and appended with "cq:dialog" to construct the target path of the resource provider root location.   A resource provider service is constructed and registered at runtime with this location, such that any requests to this resource are relative to the generated synthetic form resource.  

An additional optional feature is to disable sling merger behaviors so that there are no additional form elements (to be decided on later) -- this is likely not a big deal for components but if using this feature on pages it will be necessary to prevent additional garbage from showing in the generated form.

The result is that a developer only need create a sling model with proper annotations and the dialog is then always correct and always relevant to the model.  There is no need to update a secondary location every time the component needs to be updated or revised.

![image](https://user-images.githubusercontent.com/5144198/58193888-1a4f8800-7c92-11e9-94eb-3436a0963ef1.png)

**Comment by badvision** [comment]
@klcodanr, @HitmanInWis , @davidjgonzalez  this is the not-yet-added feature I was describing in the other recent PR's.  Those PR's do not include this feature but do support its eventual addition, but those PRs mostly just fix current bugs which would otherwise impede the success of a feature such as this.

**Comment by joerghoh** [comment]
Sounds good and definitely something we should add. Might not solve all issues with generating dialogs, but for the majority of the simple component dialogs it's probably sufficient.

Some questions:
* you register a ResourceProvider for each of these models? Have you already tested if this has an performance impact on general resource lookup? Or would it be possible to register a single ResourceProvider to handle all of these models?
* You use the ``@inject`` annotation to inject the properties from the Resource's ValueMap, but there are other ways to get them as well (e.g. ``@ValueMapValue``), can you handle them as well?
* What about Models which use other means than the Resource to get data from?

I think that this is a nice way to help reduce the boilerplate, but we should provide good documentation and include its limits.

**Comment by davidjgonzalez** [comment]
@badvision is the intent to use this API in building-out custom AEM Components and replace (via auto-generation) dialogs defined via JCR nodes? 

If so, does this have feature parity with the JCR node definition approach? How does this play with extending Core Components?

We shouldn't be replacing supported-by-Adobe AEM development best practices; this smells like it might be doing that? is it?

**Comment by gutsy** [comment]
I love this idea, creating dialogs (and especially touch UI dialogs) is tedious and unfun.

**Comment by klcodanr** [comment]
So my concern is similar to @davidjgonzalez . While I think this is a problem that would be great to solve, providing another way to programmatically generating a dialog seems to be fraught with maintenance and upgrade issues. 

IMO -- it would be cleaner to support the generation of the dialogs "offline" e.g. either through some sort of dialog builder or dialog / resource DSL which makes the process less "unfun"

**Comment by badvision** [comment]
Core components still work the same way they always work, this is really more for things like custom components that require a tedious amount of custom dialog generation.  I'm not trying to replace what the product is doing.  I'm actually just trying to do something better and more efficient.

**Comment by HitmanInWis** [comment]
I also love this idea, as dialog coding is super tedious and error prone.  However, I agree the more effective and flexible approach may instead be a way to generate the code offline to be put into a codebase, and then deploy to AEM.  This opens up opportunity for generating the simple 80% of a complex component, allowing the last 20% to be hand-baked, while also supporting 100% generation for simple components.  Supporting things like configs to extend an existing WCM Core component using the proxy extension method would be easy add-ons.

Bounteous is going to be open sourcing in the next day or so a generator we've built over the past month to do just this.  It takes in a JSON file of attributes and kicks out:
- Full _cq_dialog, dialogshared, and dialogglobal dialogs (the latter two being for Shared Component Props)
    - Supports all basic field types
    - Supports image fields
    - Supports multifields
- Clientlib at the correct /site folder path under the component
- HTL file that pulls in the sling model and also displays the default WCM Core template if component is not configured
- Fully coded sling model java classes (interface and impl)

One key difference in approach (which means both @badvision and Bounteous' approach may actually *both* be valid) is that Bounteous' approach supports a Front End Dev-first/only mentality, which has been a real challenge since the introduction of sling models.  @badvision's approach on the other hand can be valid for Back End-only Dev, where coding of sling models is a natural starting point.

**Comment by bstopp** [comment]
Doesn't this design assume a 1:1 mapping between a Sling Model and a Component's Dialog?

**Comment by badvision** [comment]
Only for the things which you put a form field annotation on.   It's entirely possible to have other things in your sling model which are not present or visible in a form.

**Comment by badvision** [comment]
This approach is incremental, building on stuff that MCP was already doing basically.  The feature itself is just for the resource provider.  The hard part of generating dialogs is already in ACS Commons.

**Comment by bstopp** [comment]
I'm on the side of: if we're got to generate a dialog, then it as part the build cycle is the appropriate approach. 

Unless/until the Product team has stated that synthetic dialog generation is a supported feature/design paradigm, we should stick to what is supported. To me this means - repository nodes defining the structure.

Who knows what upgrade challenges this approach may lead to down the road.

**Comment by badvision** [comment]
Ok so let's break this down a little more: This is actually better than what the product does today.  Why?  Because it still uses only the supported granite components, just like your dialogs do, however if the product changes how those work then only this generator has to change.  Whereas if the product changes what components are allowed or how dialogs are structured, then you have to go rewrite all your dialogs by hand.  In this sense, my approach is far safer and is easier to update or future-proof.

**Comment by bstopp** [comment]
`however if the product changes how those work then only this generator has to change` < this would also be true if it was a build-time generation, and not run-time.

**Comment by badvision** [comment]
@joerghoh the @inject stuff is because it's a sling model, not required for form generation.  It is, however, required for another framework feature that I'm not going to introduce into ACS Commons, but rather donate to Sling (if they'll have it) for JCR Transparent Persistence.

**Comment by badvision** [comment]
> `however if the product changes how those work then only this generator has to change` < this would also be true if it was a build-time generation, and not run-time.

Have you been on an upgrade project that required recompiling code and what seemed it would be a simple 5-minute developer task?  Trust me, no, don't write things that require that.  It becomes an upgrade barrier, even if it seems like it shouldn't.

**Comment by bstopp** [comment]
>> however if the product changes how those work then only this generator has to change < this would also be true if it was a build-time generation, and not run-time.

>Have you been on an upgrade project that required recompiling code and what seemed it would be a simple 5-minute developer task? Trust me, no, don't write things that require that. It becomes an upgrade barrier, even if it seems like it shouldn't.

I don't see how this would be different - if build-time generation is a ridiculously costly upgrade task, then run-time generation is just as costly. The changes that need to be made would be the same LoE.

Run-Time (this) would require 2x effort to maintain for upgrade purposes - as when an update occurs, in this library, we would be required to maintain both versions of logic until we choose to deprecate and remove. A non-trivial amount of work, as when this library drops support for each legacy version of AEM.

Build-time generation is safer for upgrading because when I run a build, i can pick which version of the plugin/tool i want to use. This will directly target my AEM product version. The compatibility would be built into the release cycle. 1.x = AEM 6.x, 1.y=AEM6.y. When a new release for new AEM would be needed, you simply drop support for the prev version. The library only contains the support needed for the targeted platform, not every version of the product.

**Comment by badvision** [comment]
I can make the runtime aware of the installed product version and switch generators if needed.  Fortunately we're only worried about the current version of granite components.  Provided those don't change their interface (I'm basing all this on the public documentation for granite components) it should be pretty safe.  I'm going to disagree with you though, running a maven build might be simple enough for you or for me.  But there are times where administrator types try to do things like "no-touch" upgrades and anything requiring setting up maven blows the time estimates out of the water.  I'm trying to go for lowest common denominator and setting the stage for seamless updates to this stuff to avoid that kind of problem.  For example, if an admin installs a new version of ACS Commons in an upgraded environment in the future, having a custom package including an old version won't result in regressing ACS Commons to an old version.  Therefore, the old packages don't have to be rebuilt for this feature to keep working.

**Comment by badvision** [comment]
I'm sorry you guys have a preference for a different kind of feature.  Be my guest to write it however you see fit; I don't have time to and honestly I've already written it.  Happy to keep it in my private repo in case someone needs it.

**Comment by badvision** [comment]
If you do, however decide you would like this feature please feel free to re-open the issue and ping me.

**Comment by royteeuwen** [comment]
Hey @badvision , did you ever have a look at http://code.digitalatolson.com/cq-component-maven-plugin/ ?

**Comment by badvision** [comment]
I think that's great, and I can see many places it would be really useful.  Thanks for contributing that to open source!  This dialog generator was more a natural extension of stuff I already wrote as part of MCP, so it was an evolutionary step, and honestly only a hundred or so lines of code.

**Comment by joerghoh** [comment]
@badvision I would love to have this feature as part of ACS AEM Commons; and even if there are cases when another approach (e.g. the generation of the dialog as part of the build) is more suitable, there is definitely value to have this on-the-fly generation of dialog structures at hand. I know that there are many Java Backend-Developers who are required to write component dialogs for their components as well, and this tool makes it definitely easier for them.
There is no single "one-size-fits-all" solution here, and if we wait for Adobe product engineering (or even the Core Components team) to approve this approach, we wait forever. I also consider this project as testing platform to see what features are useful and might make it into the product as well.

And: the overhead of having this feature is negligible. If it is turned off by default (which is/should be the default of the most of the features in here), it does not have an impact on performance and stability.

So as a question to all participants in this thread: What speaks against having this here as a pure optional-to-use feature, as all features in ACS AEM Commons are? Next to all the other ways to define and create dialog structures.

**Comment by badvision** [comment]
It's a three day weekend over here but you will have a feature branch before Monday.  Thanks  @joerghoh !

**Comment by badvision** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/feature/Dialog-Resource-Provider

The basic implementation is in the feature branch; still needs the OSGi kill switch and some unit tests.

**Comment by HitmanInWis** [comment]
Agreed with @joerghoh's post 100%.  No harm in having extra tools available, if they work and result in negligible overhead in being present.  Great innovation @badvision.

**Comment by badvision** [comment]
Thanks @HitmanInWis!  I have updated the service to be disabled by default and enabled via OSGi configuration.  This fits in line with what we do with other opt-in features.  Still needs some unit test coverage but it does work.

**Comment by davidjgonzalez** [comment]
ACS Commons is _not_ a framework and does _not_ compete with AEM features (features/frameworks/APIs/etc). In fact, we deprecate our features when AEM introduces their own way to do the job. AFAICT this PR is a framework that directly competes with an established, supported, and more fully-featured approach to achieve the same.

Whether we **like** AEM's approach is moot. Open-source or not, relying on this framework is unnecessary lock-in, and risk: bugs/incompatibility w/ future versions/lack of feature parity/etc. 

The difference between this and other ACS Commons features is: The alternative for _other_ ACS Commons features is to "do it yourself". This alternative to this feature (framework) is to use the Adobe-supported, tried-and-true, fully-featured approach.

Perhaps this is better PR'd into Core Components (also OSS), at merge, it will be supported by Adobe and a viable framework to promote to AEM customers. Being in Core Components, you can actively engage in the work to ensure you don't "wait forever".

Hope this helps explain the concern -- it's a cool idea/innovation!

**Comment by badvision** [comment]
Core components is a separate concern though, this is more data focused whereas core components deal with actual base component implementation.  I think there could be room for both things, or folks can use this feature where needed.  It's an opt-in solution so it shouldn't mess up or step on other frameworks.

**Comment by bstopp** [comment]
> It's an opt-in solution so it shouldn't mess up or step on other frameworks.

>ACS Commons is _not_ a framework and does _not_ compete with AEM features (features/frameworks/APIs/etc).

**Comment by badvision** [comment]
Sorry I'm not familiar with what framework you're suggesting this competes with.

**Comment by justinedelson** [comment]
This seems to have bubbled into a more heated discussion than usual and while disagreement can be healthy, it is also important that everyone be respectful. To be honest, I'm not totally following some of the disagreement here, but I'm going to try to summarize what I believe is really happening:

1. AEM developers need to create dialogs for "regular" components (by "regular" here I mean components which get dropped into a page via the page or template editors).
2. There are multiple approaches to building dialogs.
3. None of those approaches are perfect. We're talking about software here, so perfection is really out of the question :)

I hope the above is not particular controversial.

If I understand correctly, what @badvision is proposing here is a _method_ for generating dialogs at runtime. Whether we want to call that a framework or a library or whatever seems unimportant to me.

Personally, I don't think #2 above is a problem. Do I think that the cq-component-maven-plugin or what's being proposed here will always produce the *best* dialogs? No, I do not. Do I think there is a class of dialogs where you can slap a few annotations on a class and get a reasonable authoring experience? Absolutely.

I see a number of what I think are off-topic issues being raised and I really think this needs to be brought back to the fundamental question... is there a place in ACS AEM Commons for runtime-generated component dialogs? Whether or not such a tool would be _universally_ useful or replace other methods for building dialogs doesn't seem like a factor -- there's plenty in this project which is used in a relatively small minority of use cases. We as a community have never really established guidelines about what should be included and what shouldn't be included, but in general I think the primary factors should be:

* Is this something which has practical application in real-world projects? i.e. this project shouldn't contain features which are uninformed by reality.
* Is someone (to the best of their ability to agree to these things in the present) willing to participate in the maintenance of the feature?
* Is the feature (to the best of the community's knowledge) unlikely to create problems for customers, especially related to product updates?

(And I'll acknowledge that I have personally violated some of this rubric. I'm looking at you Watson speech to text...)

I'm personally too far away from day-to-day AEM development to judge this on the first bullet. But the existence of the cq-component-maven-plugin suggests that there is real-world value to alternate approaches to dialog generation. On the second point, I think the answer is clear. On the third point, it is debatable, but arguably generating the dialogs at runtime is no *riskier* from an update perspective than doing it by hand (it may be less risky, but that's not important).

I would strongly caution everyone to steer clear from value judgements like "This is actually better than what the product does today." (sorry to pick on you @badvision). This isn't highly subjective and context-dependent. I think it would be more productive to judge features as purely on their merits as possible without contextualizing that judgement based on whether or not something works "better" in a particular workflow.

All of that said, I do have some practical concerns/suggestions:

* Given that the direction from Adobe is to push towards extending the core components rather than creating components from scratch, it is not really clear to me how this works in the context where you don't control the base dialog or model class. If the answer is "that's not the use case -- this is for scratch-made components," I think that's an OK limitation, but would be worth calling out. If the answer is "totally works, you have to do XYZ," that's OK too. I'm just missing what the XYZ is.
* I don't really love the need to extend a base class. I think this is OK in the context of MCP where the generated dialogs are specific to MCP, but in the "regular component" case, it seems heavy-handed. My default suggestion is "use an annotation" :) but perhaps an interface would be OK as well.
* There's no support for design dialogs. Not a big deal IMO (presumably could always be added later), but worth noting in documentation.
* One thing that might be nice (but see my comment above about needing 'practical application') is to be able to "export" a dialog definition. This is one thing in the demo I saw a few years ago of the cq-component-maven-plugin which I really liked -- if your needs grew beyond what the plugin could do, you could always take the generated xml, put it in source control and edit.

P.S. https://www.youtube.com/watch?v=rph_1DODXDU

**Comment by badvision** [comment]
Points well made, @justinedelson!

The interface vs. annotation vs. base class bit is understandable.  Let me see if there's anything in the framework that is actually mandating that or if I can make it smarter.  I don't want every subclass to have to add the same annotation if it's established in a base class, so maybe interface is the way to go.  I'll play with it.

I'm actually not sure if this plays well with core components or not.  I can say that I saw the sling resource merger trying (unsuccessfully) to inject tabs into the resulting markup, which is why I added the ability to pepper the components with disable flags to deactivate sling resource merger.  It might be very much the case that this initial version does not support inheritance/resource merger scenarios until I can find a suitable way to unit test against them.

**Comment by badvision** [comment]
Ah, I remember why I made it a subclass originally.  Before trying the resource provider route, I was trying to have all models extend a base model that provided dialogs using a more traditional resource inheritance route but it wasn't working too well.  Since the introduction of resource providers, I don't think I need that.

**Comment by badvision** [comment]
Ok, it was possible to switch to using an annotation OR a base class pretty easily.  Both now work.  The annotation might be useful for providing additional feature flags (such as experimental support for things like sling merging resource provider) in the future.
