### ISSUE TITLE
java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException not found by com.adobe.acs.acs-aem-commons-bundle

### ISSUE THREAD

**Issue by suryakand** [Adobe-Consulting-Services/acs-aem-commons#1914]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5
* [ ] ACS AEM Commons Version: 4.1.0
* [ ] Reproducible on Latest? DID NOT TRY

### Expected Behavior

The following exception should not be thrown on AEM 6.5:
`java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException not found by com.adobe.acs.acs-aem-commons-bundle [593]`

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior
While using Adobe I/O integration from acs commons, getting following exception:

`java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException not found by com.adobe.acs.acs-aem-commons-bundle [593]`

Looks like the AEM 6.5 comes with Jackson 2.9.5, but acs commons is still pointing to 2.8.4

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce
Install ACS commons on AEM 6.5 and try to invoke Adobe I/O integration (e.g. Analytics)

### Links

ACS Commons Adobe I/O integration guide: https://adobe-consulting-services.github.io/acs-aem-commons/features/adobe-io-apis/index.html

**Comment by avinashtalamanchi** [comment]
- We encountered same issue while using `acs-aem-commons 4.1.0`, found that `acs-aem-commons` bundle is not importing `com.fasterxml.jackson*.` which is why bundle is not finding `com.fasterxml.jackson*.`


- _I have created a Pull request https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2007 for the above issue as a permanent fix._

---------------------------------------------------------------------------------------------

- **FYI** -  As a temporary solution, we added missing imports to`acs-aem-commons budle` by 
creating `bundle-fragment` to our project. Below is MANIFEST.MF

```
Manifest-Version: 1.0
Bundle-SymbolicName: com.XXXXXX.XXXX.jackson-core-fragment
Bundle-Name: XXXXX Jackson-core fragment for ACS Commons
Bundle-Version: 1.97.0.201907292300
Built-By: XXXXXXXXXX
Bnd-LastModified: 1564441201141
Bundle-ManifestVersion: 2
Import-Package: com.fasterxml.jackson.core;version="[2.8,3)",com.faste
 rxml.jackson.databind;version="[2.8,3)",javax.xml.bind;version="[2.2,
 3)"
Fragment-Host: com.adobe.acs.acs-aem-commons-bundle
Created-By: 1.8.0_201 (Oracle Corporation)
Build-Jdk: 1.8.0_201
Tool: Bnd-4.1.0.201810181252
```

**Comment by badvision** [comment]
Fix is merged, thank you.   Please re-open if there are other issues related to this.
