### ISSUE TITLE
Bulk Workflow MCP Process

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1953]
It would be nice to move Bulk Workflow Manager to MCP Process. This would mean Bulk Workflow would only support Synthetic Workflow (multi-threaded).

This will help clear out `/etc/acs-commons` and reduce the need to re-creating BWM on something more modern than AngularJS. Also, worth noting per #1951 BWM running AEM Workflow on 6.5 breaks (appears to result in . a number of Oak conflicts as the WF runs on the payloads)

This UI would simplify the execution options to be:

* Query language (querybuilder, list, jcq-sql2, xpath, jcr-sql)
* Query statement
* Relative path
* Workflow model

.. Something like .. 

![image](https://user-images.githubusercontent.com/1451868/59448028-562dc700-8dd2-11e9-8adc-cbb03fa0f5f2.png)

**Comment by badvision** [comment]
One thing I've never been hip to was requiring a user to enter a query as text, but for a first pass that's fine.  Are there any other considerations we should make?  For example, we might want to consider adding reporting options (detailed vs. counts only) and a dry run option so that it's feature-parity with some of the more powerful MCP tools like Renovator.

**Comment by davidjgonzalez** [comment]
Sure you can add those features in later PR is you want. This was trying to achieve functional parity w BWM so we can start deprecating it.

A dry run flag should be pretty easy for you to add.

This feature may be moot soon anyhow so I’d think about that before investing too much time in it tho!

**Comment by badvision** [comment]
Sounds good!  Looks like we have this merged in already so I'll close this issue.
