### ISSUE TITLE
BundleDisabler should support factory configs

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#1974]
## Required Information

* [Any] AEM Version, including Service Packs, Cumulative Fix Packs
* [Any] ACS AEM Commons Version
* [Yes] Reproducible on Latest?

### Expected Behavior

We should be able to define multiple BundleDisabler configs.

### Actual Behavior

We can define only one.

### More Info

We're using the BundleDisabler in our infra setup and we want to have an additional BundleDisabler config in our code project. This means we'll have 2 BundleDisabler configs. However, BundleDisabler is not defined as a factory configuration, so this is not possible.

**Comment by joerghoh** [comment]
If we implement this enhancement the naive way, it will be a breaking change, because the PID for the OSGI configuration needs to change (from ``com.adobe.acs.commons.util.impl.BundleDisabler`` to ``com.adobe.acs.commons.util.impl.BundleDisabler-factoryName``). I am not aware of any  way to make this change backwards compatible without duplicating code or hacking workarounds.

**Comment by henrykuijpers** [comment]
We could create a LegacyBundleDisabler that could be used to track a non-factory config and register it as a factory one?

**Comment by davidjgonzalez** [comment]
@henrykuijpers whats the use case for this?rDoesnt the BundleDisabler config just take a list of bundles names? What's the advantage of splitting them up into different OSGi config files vs. adding all bundles to disable to the single list? 

Are you trying to reduce config duplication across run modes?

**Comment by henrykuijpers** [comment]
We have 2 repositories: One for system-configs (where we disable CRXDE, etc) and one for application-code (where we want to disable a specific bundle).

We would like to be able to keep those configurations separated, since we separate system configs from application-code configs.

**Comment by joerghoh** [comment]
If you ask the OSGI devs, bundles never should be disabled (why would you have them deployed them at all to this instance?). That means that the BundleDisabler itself is a workaround, which is required because Adobe suggests in the security checklist to disable a few product bundles for PROD environments.

But besides that I don't see any other need to disable bundles at all. If you need to disable project bundles, why do you deploy them at all? For the system-configs it's ok (you implement the Adobe security checklist), but for the application-config I don't understand why you need to disable bundles there as well.

**Comment by henrykuijpers** [comment]
Another use-case came up: We're having the following configuration:
```
bundles="[org.apache.sling.jcr.webdav,org.apache.sling.jcr.davex,com.adobe.granite.crx-explorer,com.adobe.granite.crxde-lite]"
```
which we use to disable the bundles that the Adobe security checklist mentions. However, locally, we don't do this:
```
bundles="[]"
```
(as it is (was: https://issues.apache.org/jira/browse/SLING-8548) impossible to have a configuration apply to all environments, except for the local environment)

However, we have noticed that after installing AEM 6.4.8 CFP2 (or 3?), some services related to Social Sync and Livefyre become active by default. We would like to disable those bundles. 
This leaves us having to duplicate that configuration and add those 2 bundles to both of the configs mentioned above here. We would like to add a separate configuration which has the sole purpose of disabling those 2 bundles on all environments.
