### ISSUE TITLE
Feature Review: AEM Dialog Editor

### ISSUE THREAD

**Issue by ahmed-musallam** [Adobe-Consulting-Services/acs-aem-commons#1983]
I've built this: https://blogs.perficientdigital.com/2019/07/08/aem-dialog-editor/
And here is the repo for it, with initial code that most likely needs refactoring: https://github.com/ahmed-musallam/AEM-Dialog-Editor

I'd love to contribute it to ACS Commons, *or Maybe ACS tools?* 

Please take a look and let me know if there is anything that I need to change to contribute it.

**Comment by davidjgonzalez** [comment]
This looks *awesome* !!!  ... I think ACS Tools would be a better candidate since this is squarely a dev tool.  That said, ACS Tools seems to not be as well used (I assume because its "yet another package to install").  I'd be curious if, as time has passed, folks have thoughts of if/how the consolidation of the projects could be done appropriately.

Certainly nothing immediate (and I haven't looked at the code yet :)) .. but it'd be cool if this could be pulled into the IDE (for example, a few months ago I made an Intellij frontend for AEM Fiddle).

**Comment by kwin** [comment]
Looks really nice, but definitely belongs to ACS Tools. Such tools should not be installed on production servers.

**Comment by ahmed-musallam** [comment]
good points! I'm closing this and will make a contribution to ACS tools.

@davidjgonzalez I agree! pulling this into IDE would be perfect! the source of truth becomes the source-code, instead of it being the JCR. Any pointers on designing this so that it is *IDE plugin friendly* ?
