### ISSUE TITLE
Cannot open MCP item dialog in Firefox

### ISSUE THREAD

**Issue by gutsy** [Adobe-Consulting-Services/acs-aem-commons#2058]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __6.5_____
* [ ] ACS AEM Commons Version: __4.1.0___
* [ ] Reproducible on Latest? yes

### Expected Behavior
MCP task list should show and be clicked to get dialog with options to view report or download. 

### Actual Behavior

During initial load of content, this error occurs in the console:
XML Parsing Error: syntax error
Location: http://localhost:4502/etc/acs-commons/manage-controlled-processes/jcr:content.list.json
Line Number 1, Column 1:

When clicking on an item to open the dialog, this error occurs and no dialog opens:
TypeError: this._syncProp is not a function
TypeError: diag.show is not a function

### Steps to Reproduce

Open MCP tools and run a process if you have nothing in the list. After it's run, try to open the item from the list.

**Comment by badvision** [comment]
Very bizarre.  In the client lib code that creates the dialog, the object is correctly defined.  Then it is added to the DOM of the document.  After that command is processed, the object is downgraded to an HTML element and the show() method isn't available because the prototype is no longer the Coral.Dialog.  Because of this, it throws an error that show() is not a declared method.  I suspect this is mostly a firefox bug but I can't for the life of me figure out how to get around it except to not append the element to the DOM in firefox.

**Comment by badvision** [comment]
Seems that removing the line of code that inserts the Dialog into the DOM is sufficient to fix this in firefox and doesn't appear to affect Chrome.

**Comment by badvision** [comment]
No idea about that xml error.  Seems benign.
