### ISSUE TITLE
4.3.4 release doesn't have packages

### ISSUE THREAD

**Issue by Ronald-Diemicke** [Adobe-Consulting-Services/acs-aem-commons#2078]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: all
* [X] ACS AEM Commons Version: 4.3.4
* [X] Reproducible on Latest? **yes**/no

### Expected Behavior

Current release package binaries are missing from the release page.

### Actual Behavior

These files should be there.

### Steps to Reproduce

https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-4.3.4 

You'll notice only the source is downloadable.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
Sorry about that, my fault!  In the near term you can always find them in bintray.  https://bintray.com/acs/releases/acs-aem-commons/4.3.4#files/com/adobe/acs

**Comment by badvision** [comment]
Updated the release with binaries.  Note: The apps and content packages are now split as this is considered the in-vogue best practice.  This will affect any projects that include ACS Commons packages directly.  If you deploy ACS Commons separately from your other packages then you should just note there are two packages instead of one now.
