### ISSUE TITLE
Content Model Framework = interpret default value of a boolean as true if checkbox is set to be checked

### ISSUE THREAD

**Issue by gutsy** [Adobe-Consulting-Services/acs-aem-commons#2084]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5
* [ ] ACS AEM Commons Version: latest
* [ ] Reproducible on Latest? yes

### Expected Behavior

In the content model framework, the default value of a checkbox should be considered true if the options has checked set to have it checked by default. 

### Actual Behavior

This does not happen, and you are required to set the bool as true AND the checkbox to be checked. That is redundant.

**Comment by badvision** [comment]
This mostly affects cases where the class is being used outside of an actual form, e.g. in a unit test.  The challenge here is that the form components themselves only operate on the field declarations and not field+object (which means they don't ever have any reason to access the original objects themselves.)

The most appropriate thing to do here is update the API to pass in the actual objects during the init phase and perform the processing there.  Doing this would be a major API increase, so I'm going to park this one for now.  In the meantime I've added a partial fix which uses the default value of the boolean field to determine if the checkbox should be checked by default.  This only works if the declaring class has a public no-parameter constructor, or if the constructor can gracefully handle nulls as inputs without throwing an error.  That's because the only way to read a declared value of a field is to instantiate an object of the declaring class, etc.
