### ISSUE TITLE
RTE within a multifield is not showing the previously stored content when we edit the component

### ISSUE THREAD

**Issue by venkat559** [Adobe-Consulting-Services/acs-aem-commons#2102]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ____AEM 6.3.3.6___Service Pack -SP3  
* [ ] ACS AEM Commons Version: ___3.17.0__
* [ ] Reproducible on Latest? yes

### Expected Behavior

RTE within a multifield should store the previously stored content when we edit the component

### Actual Behavior

RTE within a multifield is not showing the previously stored content when we edit the component

### Steps to Reproduce

Configure a RTE within a multifield and use “Source Edit” to place/store HTML content and save the dialog and re-open the dialog to edit, then  placed HTML content in "Source Edit" is not storing and becomes empty field with no data.

**Comment by johnb4** [comment]
My understanding is that the issue is that it's not properly reading the JSON_STORE values from the content node and restoring the values as they should be displayed in the configuration dialog of the component. Saving the data using the POST request seems to work fine, but when reopening the component dialog it is failing to read or parse the JSON data and populate the dialog. This worked fine with AEM 6.3 SP2 but stopped working when SP3 was installed.

**Comment by anilkumar19934** [comment]
I am also facing same issue .Can any one give me a suggestion.

Thanks in Advance
