### ISSUE TITLE
Travis job is terminated because log is too long

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2122]
When working on #2104 I came across 2 Travis jobs, which failed because:

```
The job exceeded the maximum log length, and has been terminated.
```
(java8: https://api.travis-ci.org/v3/job/616262441/log.txt)
(java11: https://api.travis-ci.org/v3/job/616262446/log.txt)

In both cases it is the job with the parameter ```POST_COVERAGE=true```.

We should try to reduce the amount of output created by our test suite. Worst case would be to disable logging for these 2 jobs.

**Comment by badvision** [comment]
There are a lot of tests with non-fatal errors that dump out a lot of stacktraces.  Like your improvements to file asset ingestor, I suspect there's other possible improvements that could be made.

A lot of the MCP-based tools have a non-fatal failure at the end of tests because it's trying to persist the reports from the test.  Either satisfying preconditions for that to work (e.g. replacing usage of JcrUtils with something else) or bypassing the report generation entirely could help a number of these cases.

**Comment by joerghoh** [comment]
As soon as #2104 is merged, I plan to add some more improvements to reduce the output of unittests.

**Comment by joerghoh** [comment]
See #2124

**Comment by joerghoh** [comment]
Additional PR #2128 

Logs are already much better than at the beginning.

**Comment by joerghoh** [comment]
As #2128 is merged, we should close this issue.
