### ISSUE TITLE
ACS commons report date mandatory issue

### ISSUE THREAD

**Issue by akarru** [Adobe-Consulting-Services/acs-aem-commons#2147]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __AEM 6.4, Service package-6.4.2_____
* [ ] ACS AEM Commons Version: __4.1.0___
* [ ] Reproducible on Latest? yes/no- yes

### Expected Behavior
In ACS commons report’s search parameters we have provided field type as datepicker and given required=true which gives a mandatory symbol when it is empty.

While executing the report for the first time it works fine and when we delete the date manually and provide new date, pulls the results accordingly but the mandatory symbols doesn’t go away.

### Actual Behavior

Mandatory symbols should go away when the date is filled in.

**Comment by klcodanr** [comment]
@akarru Is this a general issue with all fields being required or _just_ date fields?

**Comment by akarru** [comment]
It is with Date fields only..

**Comment by akarru** [comment]
Could you please let us know whether someone looking into the issue..as we
didnt got any reply.
Thanks,
Anupama

**Comment by akarru** [comment]
Any update on this??

**Comment by klcodanr** [comment]
@akarru thanks for the patience. 

I've been looking into this as available. It appears to be a problem with the events that get fired when the date fields are set via the date selector vs editing the field directly. 

I haven't seen any other uses in the AEM UI exactly the same as is being used in the Report Builder. The big difference is all required fields in the AEM dialogs disable submission instead of rejecting submission. 

I will take a look at disabling the submit button if the fields are not valid and if that resolves this issue.
