### ISSUE TITLE
AEM as a Cloud Service vs QuickStart (AMS/On-Prem) Detection

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2190]
It would be nice to have internal tooling in ACS Commons that could be used to detect if ACS Commons is deployed to AEM as a Cloud Service (either a true Cloud Env or AEM SDK Quickstart env) or an AMS or OnPrem deployment.

The tooling should support 2 uses:

1) Java API that allows for in-execution detection
    ```
    if (requireAem.isCloudService()) {  ... } else { ... }
    ```
2) OSGi Service that can be used to enable/disable components entirely.
    ```
    @Reference(target="(cloud-ready=true)" scope = ReferenceCardinality.MANDATORY)
    RequireAem requireAem;

    ... OR ...

    @Reference(target="(cloud-ready=true)" scope = ReferenceCardinality.MANDATORY)
    RequireAem requireAem;
    ```

I *think* we can do this by simply looking at the Product Info Versions.... GA Cloud versions are start at `2019.12.x` and AMS/On-Prem are (currently) in the `6.x` version.

**Comment by kwin** [comment]
I like especially proposal 2. But I think the OSGi service should be more generic so that it can support arbitrary requiring either specific versions or hosting options together with the target attribute (https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Reference.html#target--). I would propose to introduce a RequireAemVersion interface with implementations having service properties `version`, `hosting` and in the future maybe others. That way one could easily depend e.g. on a specific version range or combine multiple hosting options.

**Comment by davidjgonzalez** [comment]
@kwin Ok - made some tests; Moved it to be named `RequireAem` as like that name better, and deprecated the old `AemCapabilityHelper`

**Comment by kwin** [comment]
@davidjgonzalez Can we close this now?
