### ISSUE TITLE
Feature Review - Proxy Servlet

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2297]
What are thoughts on adding a "Proxy Servlet" to ACS Commons? This feature would effectively work as:

1. ProxyServlet factor configuration defines 
    * some non-AEM HTTP Endpoint (along w/ all required HTTP request config params)
    * A way name to address this configuration
1. HTTP Client makes request to the Proxy Servlet in AEM (by name), AEM makes a HTTP call to the non-AEM HTTP Endpoint, and streams the response through AEM back to HTTP Client

Cons
- Eats an AEM thread while waiting on 3rd party system; not great for AEM Publish
- Can do this w/ Dispatcher
- Not AEM as a Cloud Service friendly as may result in long-requests and/or binary-heavy requests (depending on what you're calling)

Pros
- Helps mitigate CORS
- Simple registry fo 3rd party endpoints
- Eating threads not such a big deal on AEM Author (where named users/threads are low)

WDYT? Worth a contribs, or is this just inviting bad behavior?

**Comment by joerghoh** [comment]
Definitely worth a contribution but we should be aware of the fact, that in many cases such a feature would need customization (e.g adding custom headers, custom logic to handle response etc, limiting the number of such external requests in parallel, circuit-breakers etc).

And here starts my doubts if it's worth to add these extension points, because that's going to increase complexity of the implementation and the need for documentation of that feature; while on the other hand the core of this feature is very simple, and maybe copy&paste from an known-to-be-excellent source and modify from there is much easier to do than to customize this feature.

So rather contribute it to acs-aem-samples?

Plus we already have the FileFetcher feature, which is quite similar.

**Comment by justinedelson** [comment]
This makes me a little nervous because of the security risks of proxying requests. But if the endpoint is fixed in configuration, those risks can be minimized.

I would suggest that any documentation clearly state that CORS is the preferred approach and that proxying should only be used when CORS is not an option.
