### ISSUE TITLE
Add support for multiple CC, BCC, ... addresses in the ACS Commons Email API

### ISSUE THREAD

**Issue by rubnig** [Adobe-Consulting-Services/acs-aem-commons#2307]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5 SP4
* [ ] ACS AEM Commons Version: 4.7.0
* [ ] Reproducible on Latest? yes

There is no proper way now to add **multiple** CC, BCC, ... addresses through the ACS Commons Email API, because it doesn't handle these email addresses as a special case but just as a single String property, which of course is not a valid InternetAddress.

The underlying Email API from Sling supports multiple addresses (https://commons.apache.org/proper/commons-email/javadocs/api-release/org/apache/commons/mail/Email.html#addCc-java.lang.String-).

There is a workaround right now, but it is really hacky: constructing a custom CC/BCC header yourself and use it directly in the email template.

I would suggest to add additional methods with parameters for CC, BCC (and maybe more) in the API (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/email/EmailService.java) to add support for multiple CC, BCC addresses and then add the right addresses through the Sling Email API.

What do you guys think of this?

**Comment by joerghoh** [comment]
In that case I would recommend to redesign this API alltogether. Instead of having a simple API call which does everything I would use both the Apache Commons EMail for the general handling, and augment it with the body templating part from ACS AEM Commons, plus the mail submission. 

In that case creating a simple mail requires more lines of code, but it's much more flexible.
