### ISSUE TITLE
if i have more than 8 items in genericlists, when opening properties page will be blank

### ISSUE THREAD

**Issue by vgajend** [Adobe-Consulting-Services/acs-aem-commons#2325]
## Required Information

* [ 6.5.3] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [4.7.0 ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by vgajend** [comment]
ERROR [144.230.44.153 [1591321282497] GET /mnt/overlay/acs-commons/components/utilities/genericlist.html HTTP/1.1] libs.granite.ui.components.shell.propertiespage Unable to render properties page correctly
org.apache.sling.api.scripting.ScriptEvaluationException:

**Comment by nesreb** [comment]
@vgajend, we see the same issue.  We decided to use Tags instead of Generic List from now on.  However, I'll share the options we found to get Generic List working on 6.5.  You might already know these workarounds, but it might help others who run into this problem.

**AEM 6.5 Clean Install (i.e., not an in-place upgrade)**
Generic List seems to work fine on a clean install of AEM 6.5, but only if we've never installed a version of acs commons earlier than v4.3.4.  v4.3.4 is when they started using Touch UI for Generic List.  If an earlier version of acs commons was installed, you can try what we did to get it working:
1. Use Package Manager to uninstall all previously installed versions of acs commons.  
2. Verify in crx that jcr path /apps/acs-commons/install is empty, and if it's not, delete the acs-aem-commons-bundle jar in crx.  
3. Install a version of acs commons 4.3.4 or higher and it should work.  We tested with 4.3.4 and 4.7.0.

**AEM 6.5 In-Place Upgrade**
Downgrading to acs commons v4.3.2 worked, but then we're stuck on that version if we want to have a user-friendly Generic List editor.  We have the issue no matter what with v4.3.4 or higher and were unable to resolve it.  We did in-place upgrades (AEM v6.3 to 6.5), so that's why we chose to switch to using Tags.  As a bonus, Tags will have official Adobe support for a long time.

**Comment by sgaem** [comment]
Hi, I am facing exactly same issue is one of the server and the steps you mentioned above i follow them. I tried to clear all JSP classes cache. Restart. Everything possible. But i am still facing this issue.

**Comment by ruchimishra** [comment]
Any update on the fix for this issue?
