### ISSUE TITLE
Enhancement :  Update username for Assets Moved with Renovator JCR_LAST_MODIFIED_BY

### ISSUE THREAD

**Issue by axp235** [Adobe-Consulting-Services/acs-aem-commons#2438]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.2
* [x] ACS AEM Commons Version: 4.8.6
* [x] Reproducible on Latest? yes

### Expected Behavior
Update the JCR_LAST_MODIFIED_BY field of the assets moved by Renovator with username "Renovator".
Having a username updated for assets moved by "Renovator" helps organizations that have custom Asset workflows to exclude the assets moved from standard workflows (Activation Workflow) to control the publish of these moved assets to scene7 etc and also get a report of assets moved.

### Actual Behavior

Currently, the JCR_LAST_MODIFIED_BY is untouched.

### Steps to Reproduce

Upload a spreadsheet with a list of assets that need to be moved.

**Comment by badvision** [comment]
It sounds like a compelling feature but we have to be careful not to impose additional metadata rules on the user.  For example, jcr last modified attributes are generally updated by the product when you save changes to a node and I'm not 100% sure we can change that to something other than the user name of the current session.  On the other hand, if we apply a new property called something slightly different we can store whatever we want and achieve the desired effect.   Unfortunately over time having two last modified by fields could get very confusing because we don't know which one is more correct by looking at it.

Instead, we might consider an alternative: An option exposed to the user that, when checked, will record the timestamp in a new property like "renovator_process_time" or something like that.   This tells us two useful things: 1) That renovator did something to this content and 2) When it happened.  So we could then use a date range to narrow down the time as well, making our query even more useful.

Thoughts?

**Comment by badvision** [comment]
(it should be an optional feature that the user must opt-in, that much I'm pretty sticky about because some people might not want metadata updates of any kind because they could cause workflow triggers or other undesired side-effects)

**Comment by axp235** [comment]
@badvision 
We drew inspiration for using the "LastModifiedBy" field after looking at some code in ACS Commons.
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/4b3da3f5fdf0b59049b966bea9306d24c87d0293/bundle/src/main/java/com/adobe/acs/commons/dam/impl/ReviewTaskAssetMoverHandler.java#L145

We could go the route of adding a new property to have some constant value as we need that to exclude in workflow config. Date ranges may not be a great way to set up exclude for us. 

As for having the user opt-in if he wants the field updated, this was one of our initial ideas then we saw the User name being thrown in as constant.  Here is our proposal

We add user opt-in for updating the user-field. If they choose it we will update it with a default value "Renovator"

This provides the users not to choose "user-field" updates and if they choose for reasons similar to us they get something constant they could use as a hook for their workflows or processes.

We are open to more ideas. Thank  You!

**Comment by axp235** [comment]
@badvision  : Waiting for your thoughts on the above so we can determine how we can proceed. Please let me know if you would like more details.
