### ISSUE TITLE
[Generic Lists][Touch UI Asset Metadata Editor]- Prefixing /mnt/acs-commons/lists to the name of a generic list in the JSON path of dropdown fields doesn't work

### ISSUE THREAD

**Issue by arpithaar** [Adobe-Consulting-Services/acs-aem-commons#2479]
* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEMaaCS, 6.5, 6.4 (Not really dependent on AEM version I believe)
* [ ] ACS AEM Commons Version: 4.8.0
* [ ] Reproducible on Latest? yes/no : Yes

### Steps to reproduce

1. Navigate to Tools -> Assets->Metadata Schemas
2. Configure a dropdown field and add the options by configuring a JSON path - /mnt/acs-commons/lists/{name-of-the-generic-list}.json
3. Go to asset's properties, the dropdown field should list the options configured in the generic list

### Actual Behavior
The assets' properties ui is broken because it expects "text" in /mnt/acs-commons/lists/{name-of-the-generic-list}.json instead of "title"

Expected JSON

<img width="407" alt="Screenshot 2020-11-18 at 4 56 58 PM" src="https://user-images.githubusercontent.com/34283439/99525069-5666c480-29bf-11eb-9084-860249f8894b.png">

Actual JSON

![image](https://user-images.githubusercontent.com/34283439/99526065-bad65380-29c0-11eb-868e-c629ffdb416a.png)

**Comment by shsteimer** [comment]
@badvision It looks like this was introduced in 4.0.0 as part of https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1568/files. Assuming the asset metadata editor is the only thing using that resource provider, which I think is true, the fix should be as simple as adding `@SerializedName` annotations to the ItemImpl class at https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/genericlists/impl/GenericListImpl.java#L42 so that the field outputs as `text` and not `title` as well as not outputting the `props` object

**Comment by badvision** [comment]
PR is always welcome.  Also, when I asked around how people were using this thing prior to refactoring and nobody spoke up it would have been nice if people actually said something then.  I don't have time to work on this at the moment unfortunately, but I have a few minutes to review a PR.

**Comment by shsteimer** [comment]
If @arpithaar can work on a PR that would be great, if not I can probably do it. Was just checking with you in case you knew of other use cases for this JSON Resource Provider other than for the Assets Metadata Editor.

**Comment by badvision** [comment]
No, I actually have no idea how people use generic lists other than how it's documented in the documentation usage pages.  People have used it in many different ways but there's no notes on it other than people complaining about how it doesn't work like it used to.  :/
