### ISSUE TITLE
Thread interruption in stuck/slow commits can lead to cascade errors (Segment not found exceptions), affects FAM and MCP related tools

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2490]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5 (possibly others)
* [x] ACS AEM Commons Version: (any)
* [x] Reproducible on Latest? yes

### Expected Behavior

Halting a process in FAM or MCP should end the process as cleanly and safely as possible and leave the system in a consistent state.  Given the choice between safe termination and waiting vs. forceful termination and instability, it's better to opt for safety and let the system operator find other means for forceful restarts if absolutely mandatory.

### Actual Behavior

If a commit is waiting for segments in order to finish, and the thread is interrupted forcefully, it can cause temporary corruption (which generally resolves on AEM restart) as a series of "Segment not found" exceptions in the logs following the thread.interrupt() event.  Basically, the work is aborted immediately which is one desired effect, but risks leaving the system in an instable state.  Therefore there's not really a good line of separation between forcefully restarting AEM and forcing a single thread to terminate in this kind of extreme circumstance.

This applies to the watchdog in FAM as well as the operation of the manual Stop/Halt of a job in progress.

### Steps to Reproduce

Run something that takes a long time and has lots of commits.  Halt it before it's done.  Look for errors in the log.

**Comment by badvision** [comment]
Not to say a few really smart people didn't tell me so... (ok, so they did) but it took a very long time to find a live anecdotal example.  Essentially what is needed here is that halting a task should abort queued work, but just wait for current work to finish.  If we want to be really fancy we could try to close all resource resolvers right off the bat when the user has manually terminated the job.   Totally happy to hear suggestions @davidjgonzalez , @justinedelson , @joerghoh ...

**Comment by badvision** [comment]
One other possibility is to look at the active stack trace for a thread and see if there's a commit call in there.  If so, leave it alone.  If not... interrupt it.  This could be really useful if someone is doing something else like an HTTP request that stalls out or something.  There are some cases where we want to interrupt stuck threads, just not threads stuck waiting for Oak commits...

**Comment by davidjgonzalez** [comment]
@badvision hmm - yeh, im not sure the best way to do this, other than to not interrupt in the first place.
Asking the obvious, but: does Oak have any facilities we could lean on? I assume not since you didnt use them in the first place.

It seems odd that if this (stuck commits) is a common-enough case in Oak they would have facilities to safely remediate.

wrt to: _Essentially what is needed here is that halting a task should abort queued work, but just wait for current work to finish._

Are you missing a "not" in there? ... "a halting task should **not** abort queued work..." Is the aborting of queued work the problem? Also, if we shouldn't abort queued work, doesn't that just mean the watchdog should be removed, and let FAM kick of the work and cross your fingers AEM/Oak can do its job in a timely manner/not get stuck?

**Comment by kwin** [comment]
Partially fixed in #2660.
