### ISSUE TITLE
RequireAem should allow to differentiate between local AEM Quickstart SDK and real AEM Cloud instances

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2517]
Currently `RequireAem` only distinguishes between two types of distribution:

1. `CLOUD_READY` and
2. `CLASSIC`

(https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/db1850ea13bb0958b22f7d2d382484406313571c/bundle/src/main/java/com/adobe/acs/commons/util/RequireAem.java#L60)

The former is set for both Cloud Service SDK QuickStart and real Cloud Service. In some cases it might make sense to distinguish between those two, so I propose to add three more distributions

`CLOUD_NATIVE_IMAGE_BUILD`, `CLOUD_NATIVE` and `CLOUD_SDK_QUICKSTART`

The former should be active during building the docker images in CloudManager (i.e. ComposeNodeStore not used), while the 2nd one should be active only when running as as real cloud service (within the Kubernetes pods). 

To be able to detect those distributions one could evaluate `Session.hasCapability()` (https://issues.apache.org/jira/browse/OAK-6563, to see whether composite node store is active with `/libs` and `/apps` mounted as read-only) and check for existence of the bundle with the symbolic-name `org.apache.sling.installer.core` (only existing on Cloud SDK Quickstart).

**Comment by joerghoh** [comment]
Can you give us some more insight why this is required? I will definitely try to avoid using different codepaths for these types of environments as a consumer of AEM as a Cloud Service, because it should not affect any downstream user of AEM as a Cloud Service ( = you).

If there are differences in the observable behavior, which requires you to workaround (and that's what this is), it should get reported and fixed from Adobe.

**Comment by kwin** [comment]
This is definitely edge cases, but they are IMHO still valid, e.g. custom [SlingRepositoryInitializer](https://sling.apache.org/documentation/bundles/repository-initialization.html#slingrepositoryinitializer) which has to know if a CompositeNodeStore with read-only apps is used...
For another use case look at https://github.com/Netcentric/accesscontroltool/blob/5b6b332436e1a7b841862919df5ac1ee13403a24/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHook.java#L78
Every custom code dealing with installation of ACLs in general has to know where it runs, as the installation procedure obviously differs.

**Comment by davidjgonzalez** [comment]
@kwin you are envisioning this extra Distro to be ~exclusively used outside of ACS Commons? 

In the context of toggling on/off ACS Commons features - I think we would endeavor to use the Classic/Cloud split - and ideally, anything written for AEM CS is designed to work on both AEM SDK and AEM CS without switching code paths based on modes (as JH alludes to).

Also - would this require us to make 4 Distros?

* CLOUD_READY = Cloud OR AEM SDK (which is the current meaning of this type)
* CLOUD_READY__CLOUD = AEM as a Cloud Service (in the cloud)
* CLOUD_READY__SDK = AEM as a Cloud Service SDK
* CLASSIC = AEM 6.x

(names TBD)

**Comment by kwin** [comment]
Right now I don't see use cases inside ACS AEM Commons.

But as outlined above I would propose 5 distros (not 4) as the one used for the Docker Build Step and the one running AEM Cloud are quite different from an architecture point of view.

**Comment by davidjgonzalez** [comment]
oops - sorry! email cut the thread short of me!

I agree with @joerghoh from an academic POV  --  but I trust your use-cases/needs are real :)

I don't object as long as we clearly communicate that the new 3 distros should be used judiciously.  

WDYT @joerghoh  .. my reservation waiting for this need to be addressed by in-product changes, is this use case is very likely not priority work from the product teams, and may take a (very) long time to be addressed. If they do address them, we can always deprecate these Distro values?

**Comment by joerghoh** [comment]
I see your issue with the permissions and the AC Tool of yours. And I see the problem with applying permission during runtime of the repository. 
I see 2 ways how it could be dealt with:
* avoid the use of permissions in /libs and /apps. With ClassicUI the only realistic change to customize the UI per roles were permission in /libs and /apps, but with TouchUI you could use renderconditions in many (all?) cases to achieve the same. Do you see different needs why permissions should be applied to /libs?
* during buildtime convert all rules which you would apply during runtime on /libs and /apps into repoinit statements. That can work if you don't plan to install AC updates during runtime which try to modify the permissions in the read-only areas.

@davidjgonzalez I am fine with this, but I would really love to understand all the usecases as well. Because otherwise ACS AEM Commons again relies on a lot of implementation details, which needs to be adapted when CS changes. And if the platform changes but projects do not update ACS AEM Commons as well, there will be trouble...

**Comment by davidjgonzalez** [comment]
@joerghoh yeah - that's a good point - if the checks aren't semantically (is this the right word?:)) bound with the distro, they could change over time, resulting in the incorrect distro being reported. Not sure how probable that is, but certainly seems possible.

@kwin TBH, I suspect you might be the only user of these :) ... just double-checking that this wouldn't better added in the codebase that requires them?  (if JH's redesign suggestions arent feasible)

**Comment by kwin** [comment]
I agree, this is probably too much of an edge case to warrant an implementation inside ACS AEM Commons.
