### ISSUE TITLE
addDataInFields: Underscorejs is undefined at (only) the time of instantiation

### ISSUE THREAD

**Issue by raphaellueckl** [Adobe-Consulting-Services/acs-aem-commons#2567]
Underscorejs is not there at the time of instantiation (why? I don't know). It would be, when it is actually being used later (some events trigger the use of it). Could you have a look? I suggest a fix further below, that I agree might be a workaround.

## Required Information

* [ 6.4.8.3 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ 5.0.4 ] ACS AEM Commons Version: _____
* [ yes ] Reproducible on Latest? yes/no

### Expected Behavior

Underscorejs should be assigned and later be used.

### Actual Behavior

At the time of assignement, underscorejs is not there... later, when being used, it would be there! In our case, it could be fixed, if 

```js
var _ = window._;
```

would be removed and direct `window` access would be used instead.

So, where `_.isEmpty()` is being used, just use it like `window._.isEmpty()`. That would fix it for us, I have no idea where the problem originates from though.

Disclaimer: I am not at all familiar with AEM and I have little to no experience with it.

### Steps to Reproduce

```
Uncaught TypeError: Cannot read property 'isEmpty' of undefined
    at instanceGenerator.addDataInFields (composite-multifield.54336e358380bcd5bb63ac5a001c8947.js:519)
    at HTMLDocument.<anonymous> (composite-multifield.54336e358380bcd5bb63ac5a001c8947.js:829)
    at HTMLDocument.dispatch (jquery.0811b5e7037ada110b591bbd86240386.js:5227)
    at HTMLDocument.elemData.handle (jquery.0811b5e7037ada110b591bbd86240386.js:4879)
    at Object.trigger (jquery.0811b5e7037ada110b591bbd86240386.js:5131)
    at HTMLDocument.<anonymous> (jquery.0811b5e7037ada110b591bbd86240386.js:5861)
    at Function.each (jquery.0811b5e7037ada110b591bbd86240386.js:371)
    at jQuery.fn.init.each (jquery.0811b5e7037ada110b591bbd86240386.js:137)
    at jQuery.fn.init.trigger (jquery.0811b5e7037ada110b591bbd86240386.js:5860)
    at Object.<anonymous> (core.395eb5cc065b51b27ae2833483a01095.js:657)
```

### Links

Needs company login, so won't work.

**Comment by jasiwal** [comment]
Hi @davidjgonzalez, Is this issue fixed? No fixed version is mentioned here.
I'm getting the same issue after the AEM service pack upgrade.
AEM version: 6.5.11 & ACS Commons version: 4.3.2

**Comment by davidjgonzalez** [comment]
Can you verify how youre proxying this in? Assuming youre hooking into the provided [1] clientlib category, that establishes a dependency on `underscore`.

Can you also check that on the HTML document that loads this (i think probably the Dialog doc, assume you're using it in a regular dialog?) that there is a script include to the underscore dep?

Also, any idea if this just started happening w/ SP11? (did it work for you in previous SP's?)

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/.content.xml

**Comment by jasiwal** [comment]
Hi @davidjgonzalez, thanks for the quick reply.

1st I want to reply to your last question :) - Yes, everything was fine on 6.5.6, the 'underscore' error started as we upgraded to 6.5.11 (service pack 11).

After deep analysis, here are a few points
1- we are not hooking composite-multifield directly/indirectly in our codebase. It is getting added in authoring mode somehow. maybe through 'cq.authoring.dialog' clientLibs in edit mode.

2- Error is coming because ACS Commons is using 'underscore' dependency which is removed from AEM from 6.5.10 onward I think.
Reference 1: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/after-updating-aem-6-5-10-underscore-dependency-is-not-loading/td-p/426336
Reference 2 (search for lodash): https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/deprecated-removed-features.html?lang=en

Solution: As of now we are going to change the "underscore" to "lodash.underscore" in our codebase wherever we have used it. And also I'm going to change manually in ACS Commons 'composite-multifield' as of now until we get an update https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/.content.xml

**Comment by jasiwal** [comment]
If you agree, I'll create a new ticket for this issue?

**Comment by jasiwal** [comment]
@elfrenqv not yet. 
I think underscore support was removed unplanned. I see issues in AEM service pack 11 code also under content fragment model create functionality.

**Comment by ronnyfm** [comment]
I see this as closed, but I am not clear regarding the solution, any insights? Thanks.
