### ISSUE TITLE
 RedirectManager: problems with non-english locale

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2569]
I am testing right now on a Linux system with `LANG=de_DE.UTF-8`. When running the unittests I get a failure at

```
java.lang.NullPointerException: temporal
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1838)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817)
	at com.adobe.acs.commons.redirects.models.RedirectRuleTest.testCreateFromResource(RedirectRuleTest.java:51)

```

Changing the test to use "11 Januar 2021" as ` untilDate` the test works. So this is test has a problem with the locale. 

But going further, it should be validated that RedirectRule functionality also works independently of the underlying locale (not sure if this is the case). Just looking at the code I don't find anything, which enforces to use a fixed locale.

`ImportRedirectMapServletTest` fails for the same reason.

(Anyway, is it really required to define the untilDate as a string? Isn't it possible to use a date within JCR and map that to something which doesn't need the parsing from a String?)

**Comment by YegorKozlov** [comment]
I confirmed the issue. 

1. Build is locale-dependent and only works with the EN locale.
2. The UI saves dates as localized strings. this can end-up in a list of redirects edited from different locales, e.g.
```
05 abril 2021
05 janvier 2021
05 января 2021
```
which the backend code won't be able to parse. 

I agree it makes sense to save dates as JCR dates. Fiddling with strings is not to be relied on.
Also, it will be more flexible. So far the code rounded the dates up to the next day minus 1 second e.g. when you select a 'January 5, 2021' the code treated it as 'January 5, 2021 23:59:59'. It is not obvious and there can be cases when users will want to set exact time instead of implied 23:25:59. 

The patch is coming. I'm going to merge it into https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2564/

**Comment by YegorKozlov** [comment]
the fix is in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2564 waiting to be approved

**Comment by YegorKozlov** [comment]
The fix was merged into master
