### ISSUE TITLE
Don't implement Provider type SlingHttpServletRequest in FakeSlingHttpServletRequest

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2648]
The Sling Servlet-Helper bundle contains a MockSlingHttpServletRequest class, which serves the same purpose as the FakeSlingHttpServletRequest, which is flagged by CloudManager to implement product interfaces (see #2604).

The FakeSlingHttpServletRequest is an implementation class (not exposed) and only used by the RedirectMapModel, so it could be easily replaced with the MockSlingHttpServletRequest. 

The problem is that this bundle is not installed by default with AEM 6.x, but only on CloudService. On AEM 6.x it must be installed along with the customization.

@justinedelson is all code checked by the CM validation rules, which is going to be deployed via CM, irrespective of java package names? So if the bundle org.apache.sling:org.apache.sling.servlet-helper is added to the deployment, will the CM quality check complain about it as well (because it comes with a class implementing this interface, which is marked as @ConsumerType)?
What would be the possible solution for that? Getting this bundle into the next SP and until then asking the CSE to install the bundle manually once?

**Comment by justinedelson** [comment]
@joerghoh No, the package name/bundle name is not taken into account -- in your example there'd be no guarantee that upon an SP installation the interface wouldn't change in a way that would backwards incompatible to implementors.

It also might be worth discussing on sling-dev if @ProviderType is the right annotation for SlingHttpServletRequest. The original decision point (see https://issues.apache.org/jira/browse/SLING-2993?focusedCommentId=13729553&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13729553) was that if an interface was "intended to be implemented by a single bundle..." should be @ProviderType and if it was "intended to be implemented by multiple bundles..." it should be @ConsumerType. But here we have an example *in Sling itself* where the interface is implemented by multiple bundles yet the @ProviderType annotation is used. So @ConsumerType may be actually correct annotation and this is just a bug in Sling/AEM that needs to be fixed.

I should say that I'm not 100% sure what happens to the CM rule if (for example) an interface is @ProviderType in the 6.5 UberJar but @ConsumerType in the latest CS SDK. That might need some internal testing but to my knowledge that case doesn't actually exist (yet).

**Comment by joerghoh** [comment]
@justinedelson 

> in your example there'd be no guarantee that upon an SP installation the interface wouldn't change in a way that would backwards incompatible to implementors.

That's for sure, but if if Adobe would provide both the Sling API *and* the Servler Helpers bundle, then it would be Adobe's task to keep them in sync with matching dependencies. And a customer would just use the MockSlingHttpServletRequest and is decoupled from the evolution of the SlingHttpServletRequest interface (unless a major version update happens).

good point about the policy itself; and I am quite sure that this criteria was on no one's radar when the ServlerHelper bundle has been created. Will try to follow-up on sling-dev.

**Comment by justinedelson** [comment]
> That's for sure, but if if Adobe would provide both the Sling API and the Servler Helpers bundle, then it would be Adobe's task to keep them in sync with matching dependencies. And a customer would just use the MockSlingHttpServletRequest and is decoupled from the evolution of the SlingHttpServletRequest interface (unless a major version update happens).

That's correct. The "your example" I was responding to was the idea of adding the servlet helpers bundle to the Cloud Manager deployment. In that context, it is *not* Adobe's task to keep them in sync.

What I wanted to clarify, based on your question, is that the provenance of the implementation is not important -- either the implementation is part of the product or is deployed through CM. The idea of having a CSE install the bundle once would logically make it part of the product for these purposes.

**Comment by kwin** [comment]
> was that if an interface was "intended to be implemented by a single bundle..." should be @ProviderType and if it was "intended to be implemented by multiple bundles..." it should be @ConsumerType.

That is not sufficient. Even if there are multiple bundle implementing an interface it may still be a provider interface.

If we would change SlingHttpServletRequest to being a ConsumerType, every change in that interface would break every(!!) bundle (no matter if they just use the interface or implement it).

**Export Policy of Semantic Versioning:**

_ConsumerType_
Every binary incompatible change requires an increment on the major version.

_ProviderType_
Every binary incompatible change requires (at least) an increment on the minor version.

**Import Policy of Semantic Versioning:**
Annotation on class/interface | Version | Implemented | Import-Package Version Range | Versioning Policy
-- | -- | -- | -- | --
@ConsumerType | 1.1.0 | yes | [1.1, 2.0) | Consumer
@ConsumerType | 1.1.0 | no | [1.1, 2.0) | Consumer
@ProviderType | 1.1.0 | yes | [1.1, 1.2) | Provider
@ProviderType | 1.1.0 | no | [1.1, 2.0) | Consumer

This is obviously much worse than before, therefore there won't be a switch of the type in SlingHttpServletRequest.

**Comment by kwin** [comment]
For me CQBP-84 is questionable as it disables proper use of semantic versioning. If people want to implement provider types they should just be aware that this is more likely to break with future product updates. But the good thing is that this breakage is easy to detect thanks to Semantic versioning. There was never any rule that only certain bundles should implement provider types (until recently), so if you want to enforce that now I would rather recommend using https://github.com/apache/sling-org-apache-sling-feature-extension-apiregions/blob/master/docs/api-regions.md for that!

**Comment by cziegeler** [comment]
ProviderType vs ConsumerType is not a question of the cardinality of implementations. It is more about whether an implementation of an API will *provide* the implementation or a *consumer* of an API will implement the interface.
In many cases, this results in one implementation for a ProviderType, but there is no strict rule for that - similar there are many consumer type interfaces (think of SPIs) where there is only one implementation.

**Comment by justinedelson** [comment]
@cziegeler you are of course correct, I was simply pointing to the original intention of how the annotations would be utilized in Sling which _was_ defined in terms of cardinality (as listed in the JIRA comment I linked to). As mentioned, it is a discussion for sling-dev how strictly or loosely to follow that original intention.

@kwin your table is correct. The problem is, in that example, that AEM may release version 1.2 of this package in a minor release and thus ACS Commons (or any other custom code which implemented that interface) would no longer resolve. This has occurred already in this project at least once to my knowledge. And it has occurred in many other situations with both customer projects and 3rd party packages.

> But the good thing is that this breakage is easy to detect thanks to Semantic versioning.

Yes, it is quite easy to detect when an SP is installed and bundles do not resolve. Leaving aside issues where the import range is manually overridden, semantic versioning is working correctly.

**Comment by kwin** [comment]
@justinedelson @cziegeler What is you suggestion how to make ACS AEM Commons no longer trigger `CQRules:CQBP-84`. I am a bit out of ideas here....

**Comment by royteeuwen** [comment]
@kwin is there no way to disable the manual approve by annotating your specific implementing SlingHttpServletRequest class   (for example using SupressWarnings) ? Not on AEMaaCS yet but that sounds really annoying indeed

**Comment by justinedelson** [comment]
@royteeuwen No, `@SuppressWarnings` is not supported for this case -- this is not a false positive. There are ways of automating the approval, but that's a different subject.

**Comment by cziegeler** [comment]
Maybe we should take a step back and look at the real issue - the code is creating a  FakeSlingHttpServletRequest object to call ResourceResolver.map(). The problem is that FakeSlingHttpServletRequest is implementing SlingHttpServletRequest - however ResourceResolver map only requires a javax.servlet.http.HttpServletRequest - so changing FakeSlingHttpServletRequest  to only implement javax.servlet.http.HttpServletRequest should do the trick

**Comment by justinedelson** [comment]
nice catch @cziegeler .

**Comment by royteeuwen** [comment]
@cziegeler  we still have this issue in our project. You said in one instance to just extend the SlingHttpServletRequestWrapper, but this expects a wrapped request. We want to make a fake request without having an actual other request to wrap. Just passing null throws an exception because ServletRequestWrapper expects a request that is not null..

When trying to use the sling servlet-helpers bundle, we also get issues because the aemanalyser states that it's not available in our start level

So how do we make a mock sling http servlet request without having an actual one. And no, using a HttpServletRequest is not an option because we will be using that request to adapt from

**Comment by cziegeler** [comment]
@royteeuwen It seems you are talkling about a different use case than the one this issue is about. Right, the wrapper can only be used if you have already a request object. There is a new builder api in Sling API which allows to build SlingHttpServletRequest/Response objects; I suggest to use that one instead

**Comment by cziegeler** [comment]
Unfortunately true, but it will be part of one of the next releases

**Comment by royteeuwen** [comment]
Hey @cziegeler  I just looked into the SlingHttpServletRequestBuilder, but it seems to be missing one mayor feature, namely that you can't say withResource / withPath ? or am I missing something?

To give you a highlight of what I want to achieve that doesn't seem to be possible. I have a Sling Model that adapts from SlingHttpServletRequest, but I'm in a business logic that doesn't have any request bound to it, so I can't adapt to it (and all the AEM Core Components expect a SlingHttpServletRequest and not a Resource as adapter)

**Comment by royteeuwen** [comment]
@cziegeler  it seems that in the newly released aem-sdk (2021.11.6058.20211123T163652Z-211000) the sling.api is included as 2.24.0 so the packages are there, but they arent exported to the global api region. Could this be fixed :/ ?

**Comment by cziegeler** [comment]
@royteeuwen Yes, we did the update in two parts: first updating to latest Sling API - which is released with 2021.11.6058 - and the next update will make that package part of the global region

**Comment by royteeuwen** [comment]
@cziegeler ok clear, thanks!

If I may ask, what is actually the reasoning behind not by default adding all sling related projects to the global region? For example this specific builder is one I would have expected to be by default added because it's sling, and also the sling servlethelpers to create an InternalRequest that bypasses the sling filters (like used in graphql) is another one I saw that is not publicy / globally available. Isn't that a bit the vision of the actual open source stuff, to have that available and also be able to use / contribute to it? I definitely understand the api regions for granite / internal adobe stuff, just find it weird in my first aem as a cloud service project that a lot of stuff I am used to be able to work with is just not available anymore

**Comment by cziegeler** [comment]
As mentioned the new builder package will be added, we just split up the update to the new api from adding the package for internal reasons. Now, this is actually the advantage of Cloud Service that we now can make latest api available shortly after it has been released.
Nothing prevents you from using those apis and implementations that we don't make public as part of Cloud Service in your own projects. Regarding servlethelpers, we have some concerns with that one - which I shared several times on sling mailing lists/issues, so we don't want to promote this one to be used by customers - and that's now one of the reasons why the new builders package has been created as part of the main API.

**Comment by royteeuwen** [comment]
Yea I saw the sling mailinglists about it, so I definitely understand the reasoning behind that specific one, was more of an example.

What do you mean with "Nothing prevents you from using those api's and implementations in your own projects"? Is there a way to make api's from sling that are not by default in the Global region still available on our project at a customer who uses cloud service? 

(By the way, I definitely love the speediness of getting new api's now for cloud service, don't get me wrong ;)! )
