### ISSUE TITLE
Replace implementation of Provider Type RequestPathInfo

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2658]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/ff750e963a7ca3a1df49f4a9afa8aca4be4c63ef/bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java#L40 and https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/ff750e963a7ca3a1df49f4a9afa8aca4be4c63ef/bundle/src/main/java/com/adobe/acs/commons/synth/impl/SynthesizedSlingHttpServletRequest.java#L182 implement the provider type `RequestPathInfo`. As that leads to a critical issue in CQRules:CQBP-84 we have to find a way to not trigger this rule.

**Comment by kwin** [comment]
@cziegeler: Any idea how to circumvent running into this? AFAIK there is no `RequestPathInfoWrapper` provided by the product one could rely on.

**Comment by cziegeler** [comment]
I think the best solution is to add a RequestPathInfoWrapper to Sling API

**Comment by kwin** [comment]
That is no solution for ACS AEM Commons, because it needs to stay backwards compatible with AEM Classic 6.4 (which I fear will never get an updated bundle version of Sling API, once there is one).

**Comment by cziegeler** [comment]
ok, then I guess the only way is to avoid the implementation of that interface which I guess is not possible either

**Comment by royteeuwen** [comment]
> That is no solution for ACS AEM Commons, because it needs to stay backwards compatible with AEM Classic 6.4 (which I fear will never get an updated bundle version of Sling API, once there is one).

Why does the 6.x branch have to keep on working on AEM 6.4? The end of core support is reached for AEM 6.4 and they can keep on working on the 4.x or 5.x branch?

**Comment by kwin** [comment]
Even if we drop support for 6.4 we will have to support 6.5 which is unlikely to receive an update of the Sling API bundle either.

**Comment by kwin** [comment]
FTR: I added the wrapper to Sling in https://issues.apache.org/jira/browse/SLING-10650 but as I said, this is no short term solution.

**Comment by davidjgonzalez** [comment]
Also, FWIW - i tried using the `MockRequestPathInfo` from the Sling Servlet Helper module (which has its own problems since that doesnt ship with AEM, or atleast not all versions) - however that Sling module violates a number of @ProviderType declarations on the Sling Http request/response abstractions (since it basically re-implements many of these interfaces for mock/internal request use) - so perhaps this is a bigger issue unless somehow Sling gives itself a pass on violating the @ProviderType rules (and FWIW, Cloud Manager does not forgive it - so using the APIs in the Sling Servlet Helper APIs throws many Critical Bugs in CLoud Manager).. Not sure if we (or rather Sling) needs wrappers for "everything" or what.

**Comment by kwin** [comment]
This has been fixed in https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/1a25b353606dba8c16a40cabc621db3a261a5eb3.
