### ISSUE TITLE
ACS Commons Named Transform Image Servlet delivering blurry images

### ISSUE THREAD

**Issue by sandeepkumar89** [Adobe-Consulting-Services/acs-aem-commons#2790]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5
* [ ] ACS AEM Commons Version: ACS COMMONS 5.1.2
* [ ] Reproducible on Latest? yes 

### Expected Behavior 

we are using the Named Transform Image Servlet of ACS Commons with the below configuration to render the images in our application on the fly.
We are expecting the image quality and non-blurry images.

### Actual Behavior

Transformed image losing quality and the image looks blurry

### Steps to Reproduce

1. Start the vanilla instance.
2. Upload ACS Commons Package
3. Configure ACS AEM Commons - Named Image Transformer Factory with below configuration
          Transform Name : img-1280
          Image Transformers : resize:width=1280
                                             quality:quality=82
4. Upload attached image to DAM
5. Open the image with configured transformation like below
        /content/dam/image/00_Hero_ResearchCenter_1440x460@2x.jpg.transform/img-1280/image.jpg
6. See the quality of the image.

Query: We want to know if we have any other options to improve the quality of the image while using the Named Transform Image Servlet.

### Links

_Links to related assets, e.g. content packages containing test components_
![00_Hero_ResearchCenter_1440x460@2x](https://user-images.githubusercontent.com/35233919/154966889-36ed658a-c0ef-4617-943c-ba9c3acaa1e0.jpg)

**Comment by davidjgonzalez** [comment]
@sandeepkumar89 do you have the transformed iamge as well by any chance?

**Comment by sandeepkumar89** [comment]
@davidjgonzalez, please check the attached transformed image.

**Comment by davidjgonzalez** [comment]
@sandeepkumar89 So i think there's a couple things at play here. 1 being that the Java image library that AEM includes is a bit old, and isnt as good as the most modern image processing libs.

Few other things:

1. JPEG for this specific image isnt great. JPEG does great w/ gradients and soft lines. This is almost a vector drawin w/ hard edges. JPEG compression is does not do well w/ this, as you can see by all the blurriness around the edges.
2. When you upload the image to AEM Assets, it generates a Web rendition - which is what Name Image Transform uses by default. The problem here AEM has already scaled down the original JPEG to the smaller website (which introduces compressiona artifacts) and now youre RECOMPRESSING it with Named Image Transform, which will add more compression artifacts. You can see the Web rendition already has compression artifacts in that asset's rendition:

![2022-04-12 at 11 27 AM](https://user-images.githubusercontent.com/1451868/162999021-91e626dd-2e7d-4d7c-8d8c-e37785daa4fc.jpg)

You could change the Named Image Transform OSGi config to use the orginal rendition as the source, but probably not a great idea since Originals tend to be large (this will eat memory) and as you can see the generated Web rendition from the original is already blurry.

I think the right thing to do here is to save this to the DAM as a PNG (lossless, and handles hard edges/lines very well) - and then use NIT to transform that as needed.

![2022-04-12 at 11 33 AM](https://user-images.githubusercontent.com/1451868/162999593-ca6fe33f-094e-4c74-890b-a885f890239d.jpg)

(and keep in mind Github is changing all these attachements to JPG so there will be compression added - so try it out yourself on your AEM)
