### ISSUE TITLE
Custom Workflow extended from "Send Templated Email" being executed 11 times when linked to a launcher on delete node.

### ISSUE THREAD

**Issue by galindroid** [Adobe-Consulting-Services/acs-aem-commons#2864]
## Required Information

* AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM6.5.12 
* ACS AEM Commons Version: acs-aem-commons-4.11.0
* Reproducible on Latest? yes

### Expected Behavior

We wanted to create a simple workflow model that would allow us to send a templated email when we delete a page from our project in the author environment. We extended "Send Templated Email" to customize it because when used on a launcher on Delete nodes gave us a nullPointerException because the workflow payload was null, as we describe on the **Extra Info** section.

### Actual Behavior

When we create a AEM Workflow Launcher that triggers when a page in our project is deleted it sends this email 11 times, instead of just once. Attached log file for the error we get when this happens.

### Steps to Reproduce

Create a Workflow using Send Templated Email process step and link it to a new launcher set on "Event = Delete" and try deleting a page from a project.

### Entra info

We would like to emphasize that we have been reviewing this with the Adobe support team. For our part we believe that it is a problem with the Workflow Launchers since there is a problem with these that is that when creating them in "Event = Delete" and, when activating it, delete a page, we get a nullPointerException when recovering that node that we have deleted, because the workflow is executed after deleting it and it no longer exists. We believe that it is a bug of the product (we attach the log of the error that we get when it is sent 11 times).

As you can see in the error, we aren't getting an error from our code, which we extended from your "Send Templated Email" process. Seems to be related with the launcher logic itself.

![CapturaLog](https://user-images.githubusercontent.com/71692496/174243456-ccf1dc5e-2e10-46b4-834d-cddc38c3b128.PNG)

**Comment by davidjgonzalez** [comment]
@galindroid Youre correct the  Send Templated Email WF does not have anything in that would loop. My suspicion is that when you delete a page, every node under the page (aka its cq:Page/jcr:content tree) are rolling up and triggering your launcher. IIRC the challenge w/ launchers on Delete, is as you mention, the payload is no longer available for the Launcher to introspect so it makes some assumptions.

Can you try making a test WF Model that simply logs a statement (or you could try just adding a participant step) and see if that is triggered multiple times on a delete. If you can show that, then you can prove its not the ACS Commons WF step thats the problem but rather something in the invocation mechanism. Assuming this WF Model isnt transient, you should be able to see 11 WF instances as well in Tools > General > Workflow showing that the launcher created 11 WF instances (rather than the ACS Commons WF step looping and sending 11 emails)

Ill close this for now as this sounds like something to resolve in AEM rather than AEM CS. If you find something that points to ACS Commons WF being the problem, please re-open w/ the details!
