### ISSUE TITLE
ACS Redirect Manager Question (extensions in "redirect from") 

### ISSUE THREAD

**Issue by khaic** [Adobe-Consulting-Services/acs-aem-commons#3013]
AEM As a Cloud Service: Adobe Experience Manager 2022.10.9398.20221020T071514Z-220900
ACS AEM Commons Version: 5.4.0

Hi there,

We are currently trying to implement the ACS redirect manager on our instance.
We noticed that when the source URL (i.e "Redirect from") contains specific extensions such as:

 #|Redirect From | Redirect To | Incorrect Redirection
---|--- | --- | ---
1| /content/we-retail/([a-zA-Z]+)/([a-zA-Z]+)/(?test/test-image.pdf) | /content/we-retail/en/test/  | www.test.com/test.pdf/
2| /content/we-retail/([a-zA-Z]+)/([a-zA-Z]+)/(?test/test-image2.pdf) | /content/we-retail/en/ | www.test.com/.pdf
 
For case #1, this ends up redirecting us to /content/we-retail/en/test.pdf/ instead (as shown in table above).
The page loads fine, however the URL will incorrectly have a ".pdf" extension which would affect SEO.

For case #2, it ends up trying to load the page as a pdf document which will impact overall user navigation, since the homepage itself is not loaded, and instead the browser pdf viewer is brought up.
 
 We currently have the following resolver mappings:
     "/content/we-retail/master-content/en/?</"
    "/content/we-retail/master-content/en/(.+[^/])(\\.html)(/)?</$1/"
    "/content/we-retail/master-content/en/(.+[^/])(/)?</$1/"

Is there any further configuration changes we may need to make for this?

Many thanks in advanced! Any help is greatly appreciated!

**Comment by YegorKozlov** [comment]
You can call it a "feature". The original idea was to let users define target urls without extension and smartly append the extension if it is present in the request. For example, user requests `/content/we-retail/master-content/en/page-1.html` ( with .html extension) and the target url is `/content/we-retail/en/` (wo extension) . The Redirect Manager appends .html because it is present in the request and the Location header will be `/content/we-retail/en.html`

I agree this logic is far from ideal and can result in unexpected extension in the target urls.

There are two ways to handle it:
1. use absolute target url , e.g. [www.test.com/test.pdf/](http://www.test.com/test.pdf/)
2. Implement LocationHeaderAdjuster . It's a part of the Redirect Manager API that allows you wrap the response header before it is returned:
 ```java
package com.adobe.acs.commons.redirects;

import org.apache.commons.lang3.StringUtils;
import org.apache.sling.api.SlingHttpServletRequest;
import org.osgi.service.component.annotations.Component;

@Component
public class RemoveHtmlLocationAdjuster implements LocationHeaderAdjuster{
    @Override
    public String adjust(SlingHttpServletRequest request, String location) {

        if(location.matches("/content/we-retail/.*?/\.html")){
            return location.replaceAll("\.html", "");
        }
        return location;
    }
}```

I'm going to improve it and add a configuration flag to disable it. If checked, then the 'append extension' log will be disabled.
