### ISSUE TITLE
Need Assistance - Issue in cq:tags title, Giving Special Characters while exporting Tag report

### ISSUE THREAD

**Issue by pranaykumarpasala9** [Adobe-Consulting-Services/acs-aem-commons#3095]
Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.10.0
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes

Expected Behavior

cq:tag title should be same as tag title when we select the tags at Tags console(/libs/cq/tagging/gui/content/tags.html)
while generating Tag report, cq:tag title is being added with Special Characters randomly which is not expected.

Actual Behavior

Tag titles are getting added special characters while generating tag report.
Below are the issue details:
While generating tag report, cq:tag title is being added with Special Characters randomly.
When we check at tag title in Tags console(/libs/cq/tagging/gui/content/tags.html), title seems to be fine.
Sometimes when we do re-enter the text or adding the language for that specific tag fixes the issue and it is not making sense as the remaining tags are fine without adding language.

Steps to Reproduce

1. Go to /etc/acs-commons/exporters/tag-to-csv-exporter.html
2. Enter Tags Path as /content/cq:tags/fieldportal/
3. Clock on Download Tags CSV

**Comment by SandeepLeburuCTS** [comment]
Hi ACS Team,

We are facing this issue in our Staging & Production Environments.
Please let us know when we can connect on the same.

Thanks,
Sandeep.

**Comment by pranaykumarpasala9** [comment]
++  @Agilent AEM AMS Team ***@***.***>

Thanks & Regards,
Pranay Kumar Pasala.

**Comment by SandeepLeburuCTS** [comment]
Hi Yegor and Gatar,

Below is the hierarchy - This is one of the example
Field   Portal {{fieldportal}} | Products   {{products}} | Atomic   Spectroscopy (PL 9F AJ) {{atomic-spectroscopy}} | ICP   OES Software (PL 9F) {{as-icp-oes-software}} | ICP   Expert IIÂ Win 10 {{as-icp-oes-software-icp-expert-II-win-10}} |   |  
-- | -- | -- | -- | -- | -- | --


![image](https://user-images.githubusercontent.com/129559552/234297866-54757638-95e2-4536-8ae6-d92338632287.png)

Please let us know - If we can connect on the same..

Thanks,
Sandeep.

**Comment by Gatar** [comment]
Rather we can't connect, its open source project, not on-call tech support. 

Getting back to issue, at screenshot you have character �. It looks that you do have problem with encoding standards. `Â ` is displayed if you try to read (encode) in ISO 8891-1 non-breaking space sign saved (decoded) as UTF-8. Please fix the tags content by putting space char in broken place instead of broken char.

**Comment by YegorKozlov** [comment]
It's actually a bug in [TagsExportServlet](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/09a303b5dd17f8af1add5cf6bb80d35bd7259377/bundle/src/main/java/com/adobe/acs/commons/exporters/impl/tags/TagsExportServlet.java)

It's perfectly fine to have unicode characters in tag titles and you'd expect to see them in the exported CSV, however it's not the case. The servlet returns the data in the default iso-8859-1 encoding which converts unicode to funny characters.

The issue is that the servlet initialises the response Writer _before_  setting the encoding:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/09a303b5dd17f8af1add5cf6bb80d35bd7259377/bundle/src/main/java/com/adobe/acs/commons/exporters/impl/tags/TagsExportServlet.java#L66-L68

This has no effect. It should set the encoding first and then call response.getWriter:
```java
response.setContentType("text/csv");
response.setCharacterEncoding("UTF-8");
Writer writer = response.getWriter(); // will create output stream writer in the UTF-8 encoding
```

**Comment by Gatar** [comment]
@YegorKozlov can you please raise PR with fix?

**Comment by YegorKozlov** [comment]
The PR is https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3098

**Comment by SandeepLeburuCTS** [comment]
Please let us know if the bug is specific to ACS commons version 4.4.0  that we are using or is it applicable to latest available ACS common version as well?

**Comment by YegorKozlov** [comment]
> Please let us know if the bug is specific to ACS commons version 4.4.0 that we are using or is it applicable to latest available ACS common version as well?

It's reproducible withy the latest release as well.

**Comment by SandeepLeburuCTS** [comment]
Hello @YegorKozlov @Gatar,
Could you please confirm with which version of ACS Commons Pack will it be available..
Thanks,
Sandeep.

**Comment by YegorKozlov** [comment]
@SandeepLeburuCTS  the fix was merged into master, but not yet released.

**Comment by davidjgonzalez** [comment]
Should be out in 6.0.10 that just released! Thanks @YegorKozlov  and @SandeepLeburuCTS
