### ISSUE TITLE
Does com.adobe.acs.commons.images.impl.NamedImageTransformerImpl works with aem cloud services ?

### ISSUE THREAD

**Issue by MJDemo123** [Adobe-Consulting-Services/acs-aem-commons#3141]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _____AEM cloud__
* [ ] ACS AEM Commons Version: _____6.0.14
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

Images shall transform based on screen size 

### Actual Behavior

In my project below osgi config not working on aem cloud publish instances 

`\apps\projectname\osgiconfig\config\com.adobe.acs.commons.images.impl.NamedTransformImageServlet.cfg.json`

```
{  
  "acs.commons.namedimage.filename.pattern":"(image|img)/.(.+)",
  "prop.asset-rendition-picker-regex":"original/.(.*)" ,
  "sling.servlet.resourceTypes":["nt/file","nt/resource","dam/Asset","cq/Page","cq/PageContent","nt/unstructured","foundation/components/image","foundation/components/parbase","foundation/components/page"]
}

```

**Comment by davidjgonzalez** [comment]
@MJDemo123 technically it does (or should) - but its preferable to use AEM Cloud Service's web optimized image delivery: 

https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/web-optimized-image-delivery.html?lang=en#can-i-use-web-optimized-image-delivery-with-my-own-component%3F

The reason is NamedImageTransform transforms the image in AEM's JVM memory, which is something that should be avoided (streaming binaries through the JVM) in cloud service... that said, this is also how the OOTB Adaptive Image Transform servlet works, but that too should be used as a back-up option to web optimized image delivery.
