### ISSUE TITLE
Error page redirects to login

### ISSUE THREAD

**Issue by paulrohrbeck** [Adobe-Consulting-Services/acs-aem-commons#401]
I'm not sure if this is actually an issue or if I'm just missing something.. On my Publish instance the user gets redirected to the login page [1] when hitting a page that doesn't exist. If I'm logged in, I get the error page just fine. 
Looking at the code it sounds like this is handled in the function "doHandle404()". However, where does it actually check if we are on an Author or on a Publish instance? It seems for me it always meets the first condition:

```java
        if (this.getStatusCode(request) == SlingHttpServletResponse.SC_NOT_FOUND
                && this.isAnonymousRequest(request)
                && AuthUtil.isBrowserRequest(request)) {
```

1. It's a 404 request
2. it's anonymous (user is not logged in)
3. it's a browser request

Am I missing something or how does it check for Author/Publish?

[1] /content/geometrixx/en/toolbar/account/login.html

**Comment by paulrohrbeck** [comment]
Yes, I agree it makes sense to support OOTB behavior. 

I like your idea of a path-pattern based selection. An admin could say "these areas of the site are not access controlled (ie. don't have special permissions) and thus we do not need to authenticate the request". On the other hand you could also have a field where you specify which paths you DO need to authenticate. Sort of like exclude and include fields. Not sure if that makes it too complicated... wdyt?

**Comment by davidjgonzalez** [comment]
@paulrohrbeck Adding this functionality; Adding 2 new OSGi configs .. thinking we may want to set the default to "respond-with-404" since has been the usual behavior prior to the above "fix".

```
not-found.behavior = redirect-to-login || respond-with-404
not-found.exclusion-path-patterns = [ /content/foo/.* ]
```

* If `not-found.behavior = redirect-to-login` , then a 404'ing request to `/content/foo/bar`  result in an immediate 404
* If `not-found.behavior = `respond-with-404` , then a 404'ing request to `/content/foo/bar`  result in a redirect to login page (assuming the other usual conditions are met; anon, browser req, etc.)

Thoughts?

**Comment by paulrohrbeck** [comment]
@davidjgonzalez I didn't do any testing on it yet but it looks fine to me!

Is there a timeline for the 1.10.0 release?

**Comment by davidjgonzalez** [comment]
@paulrohrbeck mm.. it might be 1.9.4 .. reviewing the PRs most are bug fixes or "enhancements" that you could argue were "bugs" in the behavior.

I still need to test this PR out locally (its a PITA to try to unit test error page handler since so much is orchestrated by Sling)

@justinedelson thoughts? (I know we have the repo.adobe issue open which hopefully will be resolved in the next day or two)

**Comment by paulrohrbeck** [comment]
Hey @davidjgonzalez, any progress on a 1.9.4 or 1.10 release?

**Comment by davidjgonzalez** [comment]
Sorry @paulrohrbeck works been crazy! Would a release early next week for for you? I still need to test this one out and dont think ill have a chance till the weekend; if youve had a chance would love to hear the feedback.

@justinedelson WDYT? We have a handful of minor enhancements/fixes.

**Comment by justinedelson** [comment]
Early next week works for me.

**Comment by davidjgonzalez** [comment]
@paulrohrbeck 1.9.4 is out w this fix

**Comment by paulrohrbeck** [comment]
Awesome, thanks so much for your help on this!
