### ISSUE TITLE
TraversingCursor when creating ACL packages

### ISSUE THREAD

**Issue by dherges** [Adobe-Consulting-Services/acs-aem-commons#409]
Hi,

we're running into TraversingCursor warnings when building an ACL package:

```
31.01.2015 18:48:13.956 *WARN* [0:0:0:0:0:0:0:1 [1422724031258] POST /etc/acs-commons/packagers/test/_jcr_content.package.json HTTP/1.1] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 3455000 nodes with filter Filter(query=SELECT * FROM [rep:ACL], path=*); consider creating an index or changing the query
```

Guess that comes from findResources(QUERY, QUERY_LANG) in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/packaging/impl/ACLPackagerServletImpl.java#L224

What is the recommended solution? Create an index and fingers crossed that the query finishes faster? :)

What is the reason for query on ``path=*`` ?

**Comment by davidjgonzalez** [comment]
@dherges can you use Explain Query [1] and see if the query `SELECT * FROM [rep:ACL]` hits your primaryType index? Something is fishy here - and youre the second person to report this; a friend mentioned this a few days ago but I havent had a chance to investigate.

[1] http://adobe-consulting-services.github.io/acs-aem-tools/explain-query.html

**Comment by davidjgonzalez** [comment]
Also - What `path=*` are you referring to? The lack of path restrictions in the query? This is so any rep:Policy nodes get picked up; the node-type restriction should be sufficient to ensure this is a fast query unless you have thousands-plus `rep:Policy` nodes which which will implicitly make this slow.

**Comment by dherges** [comment]
> What path=* are you referring to? The lack of path restrictions in the query?

yeah, exactly. I was wondering why the query wasn't like ``SELECT * FROM [rep:ACL] WHERE path=/my-stuff/something-included-in-acl-packge``. But .. restricting the query to a path would work for resource-based ACLs, but not for principal-based ACLs?!

**Comment by dherges** [comment]
Explain Query tells:

``SELECT * FROM [rep:Policy]``

>  Query Explanation
> Warning! This query has characteristics that may cause performance issues when executed against large repositories.
> Traversal query
> [rep:Policy] as [rep:Policy] /* traverse "*" */

(same for oak:Unstructured, nt:file, sling:Folder, sling:OrderedFolder)

---

``SELECT * FROM [cq:Template]``
> Query Explanation
> Warning! This query has characteristics that may cause performance issues when executed against large repositories.
> Oak indexes used: nodeType
> [cq:Template] as [cq:Template] /* Filter(query=explain SELECT * FROM [cq:Template], path=*) */

(same for cq:Page, cq:Component, rep:User, rep:Group)

**Comment by davidjgonzalez** [comment]
@dherges it doesnt strict by path because the ACL Packager lets you define any set of "include path patterns". 

On CRX2 the nodeType query should be very fast (and path restrictions are actually evaluated post-query execution) so adding path filtering doesnt really help.

In Oak it can help in but you get the _real_ perf by hitting Indexes. Ex. if /content has 2MM pages and you want the ACLs under that, the entire tree was being traversed which will be slow.

Anyhow - hitting the rep:principalName is the most performant OOTB-supported approach.

**Comment by davidjgonzalez** [comment]
@dherges Check out the PR at #410  -- this should make ACL Packager performant on even large Oak repos. If you have thousands ~> millions of `rep:ACL` nodes/rules it will still be slow but at that point you have other problems :)

**Comment by davidjgonzalez** [comment]
@dherges also - an aside, your explain queries are expected since OOTB nodeType index doesnt collect `rep:ACL` nodes; adding it to your `nodeType` would work however could have a significant impact on your system as it re-indexes (or take a very long time to reindex), based on your repo size.

**Comment by dherges** [comment]
@davidjgonzalez  Ah, understood. Now I see the index definition of `/oak:index/nodetype``.

Thanks!

**Comment by davidjgonzalez** [comment]
@dherges FYI - ACS Commons Oak Index Manager [1] is a much nicer way (in my biased opinion ;)) for seeing what indexes are defined, rather than digging through `/oak:index`

https://www.evernote.com/shard/s2/sh/22cd3174-d998-4784-b2fb-88938131aad1/e8333d931ad108451e01eb2f8f046b2d/deep/0/Oak-Index-Manager---ACS-AEM-Commons.png

[1] http://adobe-consulting-services.github.io/acs-aem-commons/features/oak-index-manager.html
