### ISSUE TITLE
Audio file does not play using IE9

### ISSUE THREAD

**Issue by gvilcins** [Adobe-Consulting-Services/acs-aem-commons#466]
I am testing a larger audio file (~25mb) using the HTML5 audio component. After adding the file to the DAM and making sure the OGG; MP3 renditions are created, the file plays well in all browsers, except for IE9. In IE9, it only plays for a second and stops.

I tested the same MP3 audio file in a separate HTML page outside of AEM and it plays as expected.

Has anyone run into a situation like this before? Unfortunately, most of our users are running this browser...

**Comment by justinedelson** [comment]
Did you fix this because you fixed it yourself? If so, how?

**Comment by gvilcins** [comment]
Hi, no, haven't fixed it yet. I narrowed it down to only the publish instance. The author instance works fine. I'm working with Daycare now and I want to ensure that it's not a server issue before I post more here. Are you experiencing something similar?

**Comment by justinedelson** [comment]
No, I've never heard of this happening before.

One thing which might be an issue (I haven't seen it in this context, but with other media file types and IE) is that if you are using the Dispatcher and the Apache module which gzips files, IE doesn't like it when some binary file types are gzipped.

The way you would tell this was the issue is if the file played back fine when accessing the publish server directly, but not via the dispatcher.

Looking back at some dispatcher configurations I've set up, I use the line:

    SetEnvIfNoCase Request_URI  \.(?:gif|jpe?g|png|flv|mp3|m4v|ogg|mp4|zip|mov|wmv)$ no-gzip dont-vary

See http://httpd.apache.org/docs/2.4/mod/mod_deflate.html

**Comment by gvilcins** [comment]
Thanks for the tip, I will pass this information on and get back!

**Comment by gvilcins** [comment]
@justinedelson, this did the job - thanks!
