### ISSUE TITLE
New mini RTE in Touch UI dialog not working with ACS-Commons

### ISSUE THREAD

**Issue by mikeyhendy** [Adobe-Consulting-Services/acs-aem-commons#615]
Hi,

I've noticed that the new mini RTE field inside of Touch UI Dialog (CQ-40114) which was introduced with Feature Pack 6563, breaks with the ACS-Commons code in /apps/acs-commons/rte-plugins/source/dialog-plugin.js.  The JS breaks within the lines: 76-78:
            var uiSettings = this.superClass._getUISettings(options),
                toolbar = uiSettings.fullscreen.toolbar,
                feature = getUISetting();
The error is: "Uncaught TypeError: Cannot read property 'toolbar' of undefined".
This prevents the RTE menu from appearing & RTE saving.
![screen shot 2016-01-12 at 11 57 23 am](https://cloud.githubusercontent.com/assets/7391911/12251516/bb1adfb8-b923-11e5-8193-417839e9e86f.png)

Regards,
Mike.

**Comment by justinedelson** [comment]
@schoudry any ideas?

**Comment by schoudry** [comment]
ill check; @mikeyhendy can you add the dialog package and feature pack url

**Comment by kapildev111** [comment]
@schoudry 

Feature pack URL: https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq610/featurepack/cq-6.1.0-featurepack-6563

In the component touch dialog use cq/gui/components/authoring/dialog/richtext and try creating a hyperlink (not in inline editing) and save. you will notice on save, its stripping the anchor contents.

The same problem was there few months back with classic rte as well. Let me know if you need any more details

**Comment by kapildev111** [comment]
@schoudry , @justinedelson Do you guys need any more info on the above

**Comment by schoudry** [comment]
@kapildev111 should suffice, just not getting enough time to check....

**Comment by kapildev111** [comment]
@schoudry @justinedelson, Can you please let me know ETA on when this will be fixed. I am not sure on what basis you guys prioritise fixing these defects. I have seen tickets raised after this one getting traction but not this. 

This is impacting our project deliverables. Can you guys please help in fixing this

**Comment by justinedelson** [comment]
@kapildev111 do you have a patch which fixes this issue?

**Comment by schoudry** [comment]
@kapildev111 FP 6563 has dependencies

![image](https://cloud.githubusercontent.com/assets/6585493/12799305/c5f650bc-ca93-11e5-8155-40750ac0fd4a.png)

AEM 61 SP1 is now publicly available, includes 6563 [1] - can you install 61 SP1, update the ticket with issues you find and also attach the test component package you tried with mini RTE 

[1]
https://docs.adobe.com/docs/en/aem/6-1/release-notes-sp1.html
Includes touch-optimized UI update pack (Feature Pack 6563) for AEM 6.1.

**Comment by schoudry** [comment]
@kapildev111 upgraded my instance to AEM 61 SP1 (includes fp 6563) - could only reproduce the original issue reported....

`"Uncaught TypeError: Cannot read property 'toolbar' of undefined"`

happens when user configure RTE to use "inline" mode only eg.

`/libs/foundation/components/text/cq:dialog/content/items/tabs/items/text/items/column/items/text/uiSettings/cui/inline`

fixed with pull - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/654

The issue you reported - "stripping the anchor contents" is not reproducible; here are the steps followed 

https://drive.google.com/file/d/0B4d6KmbLkAumZmxPcTBFQjY0dlE/view?usp=sharing

if you can reproduce with AEM 61 SP1

1) Attach a video recording of the steps
2) Attach the component package
3) ACS AEM Commons version
