### ISSUE TITLE
Touch ui limit parsys issue: Granite.author is undefined

### ISSUE THREAD

**Issue by ahmed-musallam** [Adobe-Consulting-Services/acs-aem-commons#677]
tested on AEM 6.1 with SP1 installed.
There is an issue with the js file at: `/apps/acs-commons/touchui-widgets/source/touchui-limit-parsys.js`
error in browser console where Granite.author is undefined. The issue is because the file loads before the initialization of Granite.author

this issue can be easily fixed by adding: `window.Granite.author = window.Granite.author || {};` to the top of the file `touchui-limit-parsys.js`
Note that this line is used in many places  (OOTB) to insure we don't encounter undefined errors
eg: `/libs/cq/gui/components/authoring/clientlibs/editor`

**Comment by paul-bjorkstrand** [comment]
I think the underlying issue is that the touchui-widgets clientlib does not explicitly depend on the AEM OOTB clientlib that provides Granite.author. In this specific case, it is causing the touchui-widgets library to load too early. This in turn, causes `Granite.author` to be undefined when passed into the IIFE in touchui-limit-parsys. In the end, the trying to read the property `gAuthor.ui` causes an error, because `gAuthor` is undefined.

**Comment by paul-bjorkstrand** [comment]
I made an alternate pull request to address this in a slightly better way. Rather than just short-circuiting when `gAuthor` or its properties are undefined/null, set it to the actual reference of `Granite.author`, creating an object if necessary.
