### ISSUE TITLE
Strategy for supporting AEM 6.2

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#686]
With the upcoming release of AEM 6.2, the current version of ACS AEM Commons needs to be modified in some significant ways:

1) There needs to be a specific build compiled against the 6.2 UberJar due to a variety of major package version changes.
2) The `com.day.cq.workflow.WorkflowSession` interface has been changed in a non-backwards compatible way so the synthetic implementation must be changed to match.
3) The `org.apache.sling.event.jobs.JobProcessor` interface has been removed (was deprecated in 6.1).

Due to (1) and (2), we can no longer produce a cross-compatible version of ACS AEM Commons between 6.1 and 6.2 (let alone 6.0, 6.1, and 6.2).

Since I expect we will continue to have a significant number of users on 6.0 and 6.1, what I'm recommending is as follows:
* We leave `master` as compatible with 6.0/6.1 and release using the current versions 2.x
* We create a branch `feature/6.2-compatibility` and release a version against this branch with the version number 3.0.0.

At some point, based on feedback, we can switch this so that `master` is compatible with 6.2 and there's another branch for 6.0/6.1 compatibility.

Issues with this proposal:
* GitHub only allows for a single milestone to be attached to each issue.
* Since we need the unobfuscated UberJar, `feature/6.2-compatibility` cannot be built through TravisCI.

**Comment by bstopp** [comment]
For 2, did the Granite workflow API change as well? I haven't looked but those two were identical. Could synthetic workflows extend/consume the other interface, thus reducing the work to bring it forward?

Single milestones can be fixed by having dup issues per release version. This will create overhead tasks, but we can also default to 3.0 release, and then determine if we want to add it back to 2.x.

**Comment by justinedelson** [comment]
@bstopp I'll have to defer to @davidjgonzalez on (2), but I think we need to use the CQ workflow API in order to support the workflow processes commonly used with synth workflows. worth doublechecking as *maybe* that would allow us to support 6.1 and 6.2 simultaneously

**Comment by davidjgonzalez** [comment]
@bstopp We can't drop support of the CQ Workflow process API, else we'd wouldnt be able to use any CQ WorkflowProcesses in synth -- even dropping just the Synth impl of CQ WorkflowSession would have a trickle-down effect that would break CQ WorkflowProcess execution that may use it. 

Def worth looking into the problem a bit more though.

**Comment by justinedelson** [comment]
Let's move forward with the plan as suggested. We can iterate in the future, but I'd like to get a 3.0.0 release out.

**Comment by rohanraj14** [comment]
Hi Justin/David,

I am facing issue building my project jar in 6.2. And can see that while you also faced similar build error:
https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/builds/133937577

Can you please let me know the fix for it:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project sandiskweb.core: Compilation failure
[ERROR] error: error reading M:\mvn-repo\com\adobe\aem\uber-jar\6.2.0\uber-jar-6.2.0-apis.jar; zip file is empty

Rohan

**Comment by justinedelson** [comment]
@rohanraj14 please do not use ACS AEM Commons github issues to ask questions which aren't related to ACS AEM Commons.

In our Travis builds, that error is because Travis does not have access to the unobfuscated UberJar. We try to mitigate that by using travis branch exclusions, but those don't work well with tags, so those errors are not particularly important for us.
