### ISSUE TITLE
Rate limit exceeded - Twitter component

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#697]
Hi guys,

I currently get the message "Rate limit exceeded" from Twitter.

Now, the problem for me was that there was a slight misconfiguration, so we need to fix some stuff.

Other than that, I believe we can do a lot more to overcome these issues:

```
20.04.2016 12:52:15.499 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/es_ES/about/jcr:content/par/boxlong_0/par/twocolumn_colspan22/parsecond/twitter_feed.
20.04.2016 12:52:15.925 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/en_US/home/jcr:content/par/boxlong/par/twocolumn_colspan22/parsecond/twitter_feed.
20.04.2016 12:52:16.254 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/en_US/jcr:content/par/boxlong/par/twocolumn_colspan22/parsecond/twitter_feed.
20.04.2016 12:52:16.424 *INFO* [pool-5-thread-4] org.apache.jackrabbit.core.persistence.bundle.AbstractBundlePersistenceManager cachename=crx.defaultBundleCache[ConcurrentCache@1c533d67], elements=2801, usedmemorykb=8179, maxmemorykb=8192, access=186309, miss=76523
20.04.2016 12:52:16.587 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/es_ES/news/jcr:content/par/onecolumn/parfirst/twitter_feed.
20.04.2016 12:52:16.913 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/en_US/about/jcr:content/par/boxlong_0/par/twocolumn_colspan22/parsecond/twitter_feed.
20.04.2016 12:52:17.249 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/es_ES/jcr:content/par/boxlong/par/twocolumn_colspan22/parsecond/twitter_feed.
20.04.2016 12:52:17.577 *INFO* [pool-5-thread-4] com.adobe.acs.commons.twitter.impl.TwitterFeedUpdaterImpl Loading Twitter timeline for user TIMELINE for component /content/x/en_US/news/jcr:content/par/onecolumn/parfirst/twitter_feed.
```

As you can see, we're doing quite a lot of calls, to fetch the very same timeline! 

We shouldn't fetch the tweets per component, per path, per language copy.
_We should fetch the tweets per timeline._

If we were to do that, the above would result in 1 call to Twitter, instead of 7 or more.

**Comment by justinedelson** [comment]
While I can see the value of this optimization and would be open to a tested pull request, the usefulness of such a change seems very minor to me. The rate limit for this operation is 300 per 15 minute interval. That means that if you had 20 different components using the same timeline, you would be able to schedule an update every minute. I would suggest that if you need to update that frequently, the approach used by this component is probably not right for you anyway since the value of caching the timeline data in AEM for 60 seconds is minimal to non-existant. Using the Twitter-native widgets (with the caveat that you are limited on look and feel) would be a better approach if you truly needed to update that frequently.

**Comment by hkuiyo** [comment]
I totally agree with you.

However, the 20 components will be reached quite easily, due to language copies being created and the component being used on more than one page (the website it's now being used on has the component quite a few time).

But I agree it's not necessarily something that needs to be fixed right now. The change is indeed minor.
