### ISSUE TITLE
Responsive Column Control - Be able to use decimals

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#725]
Currently, it's not easily possible to use decimals. If you do, you will see that the class name contains a period, which makes it impossible to target the class with CSS.

Suggestion: Replace periods with underscores.

**Comment by hkuiyo** [comment]
Apparently it's possible to target the class, by using a backslach (\) to escape the period. I'm not sure of the browser support though.

**Comment by davidjgonzalez** [comment]
@hkuiyo its been awhile since i looked at this, but would it make more sense to give less impl specific css classes to the columns? Even col1, col2. col3 ... where these represent the columns left to right. 

Targeting an element using a class that is effectively an implementation detail that can be changed by authors feels very brittle. When an author adjusts a column width (authoring activity), won't the CSS (a dev artifact) stop applying?

**Comment by davidjgonzalez** [comment]
Deprecated feature (classicUI)
