### ISSUE TITLE
ACS Commons install breaks "Edit" and "Preview" buttons on site (TouchUI)

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#762]
Emily S. reports

> On my 6.2 instance, installing acs-aem-commons-content-3.1.0.zip breaks the “Edit” and “Preview” buttons when editing a Site.

This has not been confirmed/denied to be an issue in the 3.2.2 build, but worth checking out and providing a fix ASAP if exists. (I dont recall any 3.2.x code that would fix an issue like this)

**Comment by poojachauhan** [comment]
@davidjgonzalez , sometimes "edit" and "Preview" button breaks due to exceed in maximum number of Servlet and Script calls while processing a single client request.  
In http://localhost:4502/system/console/configMgr, increase the Number of Calls per Request in "Apache Sling Main Servlet". Let us know if this fixes the issue

**Comment by davidjgonzalez** [comment]
Thanks; closing w this suggestion
