### ISSUE TITLE
Extend dispatcher cache flush rules to flush pages that reference "shared" content

### ISSUE THREAD

**Issue by cpilsworth** [Adobe-Consulting-Services/acs-aem-commons#912]
When there is content that is referenced/included by a number of pages elsewhere on site (e.g. AEM forms, content fragments), those _referencing_ pages are not automatically flushed from cache when the shared content is updated.

The dispatcher cache flush rules allow flushing of one group of pages when content under another path is updated, but it is not always possible to know what is referencing the shared content.

Would you consider accepting an change to the dispatcher cache flush rules feature so that when pages under a certain path are updated, a flush could be triggered for other pages that _reference_ those pages?

**Comment by davidjgonzalez** [comment]
@cpilsworth Sure, but it should be build in a pluggable manner, so any one can development custom extensions that perform custom logic and flush as needed. You could provide the one you describe as the "first" impl of this hook.

**Comment by cpilsworth** [comment]
@davidjgonzalez That sounds like a good idea.  Does this sound ok:

Create a `DispatcherFlushActionFactoryImpl` Preprocessor configuration factory similar to [DispatcherFlushRulesImpl](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/replication/dispatcher/impl/DispatcherFlushRulesImpl.java) that would allow configuration of :
- replication action type (e.g. `invalidate` etc)
- path pattern (e.g. `/content/forms/*`)
- action name (e.g. class name?)

The actions could be references to instances of a `DispatcherFlushAction` type component loaded using whiteboard pattern.  Calls to Preprocessor.preprocess would be delegated to the action, which could then (in the example) find references and flush those resources.

**Comment by davidjgonzalez** [comment]
@cpilsworth i think so -- more i think about it, the more i like moving everything over to this pluggable framework and eventually ditching the FlushRules entirely.

Is the following ~ what you had in mind?

![cpil](https://cloud.githubusercontent.com/assets/1451868/23408144/fe75f840-fd94-11e6-9272-85b75397a5c0.png)

Few other thoughts since were rethinking this a bit...

1) Does action order matter?
2) Can/should actions be able to indicate prior state to the downstream? 
    * Ex. should actions collect and return a list of all paths they flush?
3) Double-check Replication action type and/or paths are the domain of the Factory vs the individual FlushActions.

**Comment by cpilsworth** [comment]
@davidjgonzalez that's pretty much what I had in mind.  I'm kinda split on the role of the action here:

**1) Resource gathering action** 
I was thinking of an action as something that would just gather candidates for flushing (2) that may have been impacted by the modification of some other resource.  The existing dispatcher cache flush rules implementation has a "if _this_ is flushed then flush _that_".   was thinking of something that would gather the "_that_" information. The replication action type and source path managed in the PathBaseFlushAction (3).

With this in mind, it _could_ make it more difficult to configure if the source/destination paths are split from between an ActionFactory configuration and a child Action configuration for the existing PathBaseFlushAction use case.

**2) Flush executing action**
However.... perhaps a better alternative is for the ActionFactory just to provide the "hook" into the flush event mechanism and for both the original and secondary resource flushes to be managed the action.  That potentially gives the action more flexibility on the flush parameters (e.g.  recache).  So in this case actions would _not_ just collect paths (2), they would then go on to execute the flush on those and the replication action type is defined at the action level (3).

I'm not sure the order matters in either (1).

I think I'm favouring the latter as the action has more flexibility and the configuration is in one place.

**Comment by davidjgonzalez** [comment]
@cpilsworth 

I like the idea of keeping the Flushing in the ActionFactory; it would let us add some efficiencies like tracking what has been flushed so we don't double-flush, prevent cyclic flushing, put guards in (100 flush -> INFO, 1000 -> WARN, 10000 -> ERROR). 

Maybe the FlushActions could returns a List of FlushActionItem objs that gold the path to flush, and override-able replication options (which are used for that particular flush).

I think keeping the minimum behavior of the FlushActions themselves simple (~ collect and return a bunch of paths) is key.  

Im a bit torn at what level the configuration should exist .. I tried to straw-man the configs out.. 

* ActionFactory ~= A Tenant in AEM
* FlushActions ~= Collection of use-cases for said tenant 

```
ActionFactory.siteA
paths=[/content/site-a/,/content/dam/,/conf/site-a] <- Not sure if this is even needed?
flushActions=[...(name=siteA.products)|(name=siteA.contentFragments)|(name=siteA.conf)]

PathAction.products
paths=[/etc/products=/content/site-a/products]
type=hierarchy

ReferencedAssetsAction.contentFragments 
/* If the original replicated resource exists under the left-side of paths is in 'assetTypes' then flush any pages that contain it under the right side of paths */
paths=[/content/dam=/content/site-a]
assetTypes=[contentFragment]
type=resource-only

PathAction.conf
paths=[/conf/site-a=/content/site-a]
type=hierarchy
```

we'd have to be careful wrt to tenant overlap as /content/dam -> would likely effect many tenants. Maybe we need a service 1 level above the ActionFactory that implements preprocessor than can de-dupe flush requests across *everything* ? the alternative would be to pull out the common actions into a "shared tenant" config (which requires more coordination between teams)

This turned out to be a lot harder than i initially thought :)

**Comment by cpilsworth** [comment]
@davidjgonzalez my specific requirement for this functionality has subsided.  Also, not sure if this functionality will be covered by ootb AEM for content/experience fragments.  Happy to close this, unless you see a reason to keep it open.

**Comment by ronnyfm** [comment]
@cpilsworth @davidjgonzalez Do you know what is the default behavior when publishing an Experience Fragment? Does the pages that have a reference to it get flushed as well? Thanks.

**Comment by davidjgonzalez** [comment]
XF does not “auto-flush” referencing resources; you’d want to set up your own rules to handle this

**Comment by vivekdhiman** [comment]
Does ACS provide the dispatcher flush facility such that, If any image update, the all the pages in which that image is referenced, gets automatically flushed?

**Comment by davidjgonzalez** [comment]
@vivekdhiman - unfortunately we don’t have any real intelligent lookup for what needs flushing .. it’s all have to be general path based flush schemes

**Comment by sayalic10** [comment]
Hi Team,

Recent was facing a issue related to the Adaptive Forms update on pages after publishing the changes in the Adaptive form.
The Problem Scenario is as following :
1) We are making changes to the Adaptive Forms.
2) Publishing the Forms.
3) On Publishing the Form, the form changes are not reflecting on the Pages on which the form is Authored in the Website.

Need a solution where the Dispatcher Flush Automatically invalidates the pages where the Adaptive forms is Authored on Publishing the Adaptive Form itself.

Is there any dispatcher configuration or a way we can achieve the above.
