### ISSUE TITLE
Brand Portal publication/unpublication Workflow Process

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#916]
Create a workflow process that publishes or unpublishes (possibly via a Process Arg) the payload Asset from Brand Portal. 

* (AFIAK) Currently the only trigger to publish/unpublish from BP is via the Asset Action bar button.
* It would be nice to publish (or unpublish) to brand portal as part of a Workflow.

* Handles Workflow Packages
* Skips any payloads not an Asset
* Logs a warn if Brand Portal is not configured (Is this the best behavior, or should Workflow Exception be thrown?)

It appears DamSyncService [1] can be used to publish/unpublish individual Assets

[1] https://docs.adobe.com/docs/en/aem/6-2/develop/ref/javadoc/com/adobe/cq/dam/mac/sync/api/DAMSyncService.html

**Comment by jbenn313** [comment]
This definitely seems like a worthwhile enhancement.

I have two questions about the requirements:
  - The Activate Page workflow process allows activation to be performed under the context of the latest participant in a participant workflow.  Should that also be a requirement here?
  - Are Workflow Packages commonly used?

**Comment by jbenn313** [comment]
See the link at [2] for more detail about replicateAsParticipant, mentioned in the previous comment.

[2] https://docs.adobe.com/docs/en/aem/6-2/develop/ref/javadoc/com/day/cq/wcm/workflow/process/ReplicatePageProcess.html

**Comment by jbenn313** [comment]
IMHO...
... the workflow process that does publish/unpublish should model the behavior of the OOTB ActivatePageProcess and DeactivatePageProcess, except they should act on Assets only, not pages. 
... work done to resolve this AGS issue (#916) will result in the creation of two new Workflow Processes: PublishAssetToBrandPortal and UnpublishAssetFromBrandPortal.
... if PublishAssetToBrandPortal or UnpublishAssetFromBrandPortal receive a Page as payload, an ERROR is logged.  
... if PublishAssetToBrandPortal or UnpublishAssetFromBrandPortal receive a Workflow Package as payload, an ERROR is logged.  Rationale: neither ActivatePageProcess nor DeactivatePageProcess handles Workflow Packages today.
... PublishAssetToBrandPortal or UnpublishAssetFromBrandPortal should handle replicateAsParticipant as it is handled by ActivatePageProcess and DeactivatePageProcess.  (I'm 80% convinced of this one :-) ) 
... otherwise, comply with the requirements stated at the top of this issue.

WDYT?

**Comment by davidjgonzalez** [comment]
1) agree only assets should be processed
2) would be good to handle wf packages OF assets (not activate the actual package). If yo want just handle single asset payloads I can update at the end to hand wf packages (there is a little API we have in workflowHelper that lets you iterate over each time in the wf package quite easily)

**Comment by davidjgonzalez** [comment]
Wrt to replicateAsParticipant .. Does brand portal care about who replicates it?

I assume these workflow steps would likely be added to the OOTB Request for Activation/Deactivation wf -- I can't recall of the  BP APIs even  take a username? (I don't remember that they do?)

Also - I think you can get away w just implementing the usual WorkflowProcess interface; trying to leverage ReplicatePageProcess will likely just muddy things?

**Comment by davidjgonzalez** [comment]
Closed via dc491d8392ac3341396e420b1dddd7bac7d56224
