### ISSUE TITLE
Why is ACS Commons installed in /apps instead of /libs?

### ISSUE THREAD

**Issue by hkuiyo** [Adobe-Consulting-Services/acs-aem-commons#951]
The whole Adobe framework makes creating overlays & extensions so nice.

However, ACS Commons is installed in /apps, so we cannot create overlays (unless we of course configure the search path to have an additional path).

It would make sense to me to move ACS to /libs instead of /apps.

**Comment by justinedelson** [comment]
...because /libs is reserved for the AEM product itself. Putting ACS AEM Commons's content under /libs would not be upgrade safe. I would expect that anything you want to overlay can be done by extending one of our components. If you have a specific use case which can't be supported currently, please create a specific issue for that.
